// Generated by simulator/schema/generate_schema.py. Do not edit.
// Manifest hash: c900e33092838146694ee9d797653e4f00ec45116f38784a5a4142d5e4fdff1e
#if defined(CVGAMECOREDLL_EXPORTS)
#include "CvGameCoreDLLPCH.h"
#endif

#include "VoxRlBlockView.h"

// Finds generated metadata for one declared section kind.
static const VoxRlSectionDefinition* VoxRlFindSectionDefinition(u16 sectionKind)
{
    for (u16 index = 0; index < kVoxRlSectionDefinitionCount; ++index)
    {
        if (kVoxRlSectionDefinitions[index].kind == sectionKind)
        {
            return &kVoxRlSectionDefinitions[index];
        }
    }
    return 0;
}

// Confirms that a generated block kind has a stable numeric declaration.
static bool VoxRlIsKnownBlockKind(u16 blockKind)
{
    for (u16 index = 0; index < kVoxRlBlockDefinitionCount; ++index)
    {
        if (kVoxRlBlockDefinitions[index].kind == blockKind)
        {
            return true;
        }
    }
    return false;
}

// Returns whether a block kind is transported through the 1 MiB pipe payload path.
static bool VoxRlIsPipeBlockKind(u16 blockKind)
{
    return blockKind == VOX_RL_BLOCK_CAMPAIGN || blockKind == VOX_RL_BLOCK_REQUEST ||
        blockKind == VOX_RL_BLOCK_RESULT || blockKind == VOX_RL_BLOCK_REPLAY_PLAN;
}

// Checks the generated section count rule and any caller-provided live dimension counts.
static bool VoxRlHasValidSectionCount(
    const VoxRlSectionDefinition& definition,
    const VoxRlSectionDirectoryEntry& entry,
    const VoxRlBlockValidationOptions* options)
{
    if (definition.countRule == VOX_RL_SECTION_COUNT_SINGLE && entry.count != 1)
    {
        return false;
    }
    if (definition.countRule == VOX_RL_SECTION_COUNT_BYTES && entry.count != entry.byteLength)
    {
        return false;
    }
    if (options != 0 && definition.countRule == VOX_RL_SECTION_COUNT_PER_PLOT &&
        options->checkPlotCount && entry.count != options->plotCount)
    {
        return false;
    }
    if (options != 0 && definition.countRule == VOX_RL_SECTION_COUNT_PER_ALIVE_TEAM &&
        options->checkAliveTeamCount && entry.count != options->aliveTeamCount)
    {
        return false;
    }
    return true;
}

// Finds one validated directory entry without exposing unchecked image bytes.
static const VoxRlSectionDirectoryEntry* VoxRlFindDirectoryEntry(
    const VoxRlSectionDirectoryEntry* directory,
    u16 sectionCount,
    u16 sectionKind)
{
    for (u16 index = 0; index < sectionCount; ++index)
    {
        if (directory[index].kind == sectionKind)
        {
            return &directory[index];
        }
    }
    return 0;
}

// Checks that one byte range stays inside an image without wrapping its offset.
static bool VoxRlIsImageRange(u32 offset, u32 length, u32 imageSize)
{
    u32 end = 0;
    return VoxRlAddU32(offset, length, end) && end <= imageSize;
}

// Checks all required generated sections for the selected block kind.
static bool VoxRlHasRequiredSections(
    const VoxRlSectionDirectoryEntry* directory,
    u16 sectionCount,
    u16 blockKind)
{
    for (u16 index = 0; index < kVoxRlSectionDefinitionCount; ++index)
    {
        const VoxRlSectionDefinition& definition = kVoxRlSectionDefinitions[index];
        if (definition.blockKind == blockKind && definition.required != 0 &&
            VoxRlFindDirectoryEntry(directory, sectionCount, definition.kind) == 0)
        {
            return false;
        }
    }
    return true;
}

// Validates every generated portable bool in present record sections.
static bool VoxRlValidatePortableBools(
    const u8* image,
    const VoxRlSectionDirectoryEntry* directory,
    u16 sectionCount)
{
    for (u16 definitionIndex = 0; definitionIndex < kVoxRlBooleanDefinitionCount; ++definitionIndex)
    {
        const VoxRlBooleanDefinition& definition = kVoxRlBooleanDefinitions[definitionIndex];
        const VoxRlSectionDirectoryEntry* section = VoxRlFindDirectoryEntry(directory, sectionCount, definition.sectionKind);
        const VoxRlSectionDefinition* sectionDefinition = VoxRlFindSectionDefinition(definition.sectionKind);
        if (section == 0)
        {
            continue;
        }
        if (sectionDefinition == 0 || sectionDefinition->recordSize == 0)
        {
            return false;
        }
        u32 fieldEnd = 0;
        if (definition.elementCount == 0 || definition.stride == 0 ||
            !VoxRlMultiplyU32(static_cast<u32>(definition.elementCount - 1), static_cast<u32>(definition.stride), fieldEnd) ||
            !VoxRlAddU32(fieldEnd, static_cast<u32>(definition.offset) + 1U, fieldEnd) ||
            fieldEnd > sectionDefinition->recordSize)
        {
            return false;
        }
        for (u32 recordIndex = 0; recordIndex < section->count; ++recordIndex)
        {
            u32 recordOffset = 0;
            if (!VoxRlMultiplyU32(recordIndex, sectionDefinition->recordSize, recordOffset))
            {
                return false;
            }
            for (u16 elementIndex = 0; elementIndex < definition.elementCount; ++elementIndex)
            {
                u32 elementOffset = 0;
                if (!VoxRlMultiplyU32(static_cast<u32>(elementIndex), static_cast<u32>(definition.stride), elementOffset) ||
                    !VoxRlAddU32(recordOffset, static_cast<u32>(definition.offset), recordOffset) ||
                    !VoxRlAddU32(recordOffset, elementOffset, elementOffset))
                {
                    return false;
                }
                if (image[section->offset + elementOffset] > 1)
                {
                    return false;
                }
            }
        }
    }
    return true;
}

// Validates generated parent-to-list ranges without naming any record field.
static bool VoxRlValidateRanges(
    const u8* image,
    const VoxRlSectionDirectoryEntry* directory,
    u16 sectionCount)
{
    for (u16 definitionIndex = 0; definitionIndex < kVoxRlRangeDefinitionCount; ++definitionIndex)
    {
        const VoxRlRangeDefinition& definition = kVoxRlRangeDefinitions[definitionIndex];
        const VoxRlSectionDirectoryEntry* parent = VoxRlFindDirectoryEntry(directory, sectionCount, definition.parentSectionKind);
        const VoxRlSectionDirectoryEntry* child = VoxRlFindDirectoryEntry(directory, sectionCount, definition.childSectionKind);
        const VoxRlSectionDefinition* parentDefinition = VoxRlFindSectionDefinition(definition.parentSectionKind);
        if (parent == 0)
        {
            continue;
        }
        if (child == 0 || parentDefinition == 0 || parentDefinition->recordSize == 0 ||
            definition.firstOffset + 4U > parentDefinition->recordSize ||
            definition.countOffset + 4U > parentDefinition->recordSize)
        {
            return false;
        }
        for (u32 recordIndex = 0; recordIndex < parent->count; ++recordIndex)
        {
            u32 recordOffset = 0;
            if (!VoxRlMultiplyU32(recordIndex, parentDefinition->recordSize, recordOffset))
            {
                return false;
            }
            const u8* record = image + parent->offset + recordOffset;
            const u32 first = VoxRlReadU32(record + definition.firstOffset);
            const u32 count = VoxRlReadU32(record + definition.countOffset);
            u32 rangeEnd = 0;
            if (!VoxRlAddU32(first, count, rangeEnd) || rangeEnd > child->count)
            {
                return false;
            }
        }
    }
    return true;
}

// Validates generated stable identifiers where a manifest supplies the metadata.
static bool VoxRlValidateStableIds(
    const u8* image,
    const VoxRlSectionDirectoryEntry* directory,
    u16 sectionCount)
{
    for (u16 definitionIndex = 0; definitionIndex < kVoxRlStableIdDefinitionCount; ++definitionIndex)
    {
        const VoxRlStableIdDefinition& definition = kVoxRlStableIdDefinitions[definitionIndex];
        const VoxRlSectionDirectoryEntry* section = VoxRlFindDirectoryEntry(directory, sectionCount, definition.sectionKind);
        const VoxRlSectionDefinition* sectionDefinition = VoxRlFindSectionDefinition(definition.sectionKind);
        if (section == 0)
        {
            continue;
        }
        if (sectionDefinition == 0 || definition.width != 4 || definition.offset + definition.width > sectionDefinition->recordSize)
        {
            return false;
        }
        for (u32 recordIndex = 0; recordIndex < section->count; ++recordIndex)
        {
            u32 recordOffset = 0;
            if (!VoxRlMultiplyU32(recordIndex, sectionDefinition->recordSize, recordOffset))
            {
                return false;
            }
            const u32 value = VoxRlReadU32(image + section->offset + recordOffset + definition.offset);
            if (definition.allowZero == 0 && value == 0)
            {
                return false;
            }
            for (u32 earlierIndex = 0; earlierIndex < recordIndex; ++earlierIndex)
            {
                u32 earlierOffset = 0;
                if (!VoxRlMultiplyU32(earlierIndex, sectionDefinition->recordSize, earlierOffset) ||
                    VoxRlReadU32(image + section->offset + earlierOffset + definition.offset) == value)
                {
                    return false;
                }
            }
        }
    }
    return true;
}

// Creates an empty view with a successful neutral status.
VoxRlBlockView::VoxRlBlockView()
{
    Reset();
}

// Clears all pointers before a new validation attempt.
void VoxRlBlockView::Reset()
{
    bytes_ = 0;
    byteLength_ = 0;
    frameHeader_ = 0;
    imageHeader_ = 0;
    directory_ = 0;
    status_ = VOX_RL_BLOCK_OK;
}

// Clears all view state while retaining the precise validation failure.
bool VoxRlBlockView::Fail(VoxRlBlockStatus status)
{
    bytes_ = 0;
    byteLength_ = 0;
    frameHeader_ = 0;
    imageHeader_ = 0;
    directory_ = 0;
    status_ = status;
    return false;
}

// Validates one framed portable image before any section accessor becomes available.
bool VoxRlBlockView::Open(const void* rawBytes, u32 availableBytes, const VoxRlBlockValidationOptions* options)
{
    Reset();
    if (rawBytes == 0)
    {
        return Fail(VOX_RL_BLOCK_NULL_BYTES);
    }
    if ((reinterpret_cast<size_t>(rawBytes) & (kVoxRlAlignment - 1)) != 0)
    {
        return Fail(VOX_RL_BLOCK_UNALIGNED_BYTES);
    }
    if (availableBytes < sizeof(VoxRlFrameHeader))
    {
        return Fail(VOX_RL_BLOCK_TRUNCATED_FRAME);
    }
    const u8* bytes = static_cast<const u8*>(rawBytes);
    const VoxRlFrameHeader* frame = reinterpret_cast<const VoxRlFrameHeader*>(bytes);
    if (frame->magic != kVoxRlFrameMagic)
    {
        return Fail(VOX_RL_BLOCK_BAD_MAGIC);
    }
    if (frame->protocolVersion != kVoxRlProtocolVersion)
    {
        return Fail(VOX_RL_BLOCK_BAD_PROTOCOL_VERSION);
    }
    if (frame->payloadLength > kVoxRlMaximumImageBytes)
    {
        return Fail(VOX_RL_BLOCK_BAD_PAYLOAD_LENGTH);
    }
    u32 completeLength = 0;
    if (!VoxRlAddU32(static_cast<u32>(sizeof(VoxRlFrameHeader)), frame->payloadLength, completeLength) ||
        completeLength > availableBytes)
    {
        return Fail(VOX_RL_BLOCK_TRUNCATED_IMAGE);
    }
    if (frame->payloadLength < sizeof(VoxRlImageHeader))
    {
        return Fail(VOX_RL_BLOCK_TRUNCATED_IMAGE);
    }
    const u8* image = bytes + sizeof(VoxRlFrameHeader);
    const VoxRlImageHeader* imageHeader = reinterpret_cast<const VoxRlImageHeader*>(image);
    if (!VoxRlGeneratedLayoutMatches())
    {
        return Fail(VOX_RL_BLOCK_BAD_LAYOUT);
    }
    if (imageHeader->schemaVersion != VoxRlSchemaVersion)
    {
        return Fail(VOX_RL_BLOCK_BAD_SCHEMA_VERSION);
    }
    if (!VoxRlBytesEqual(imageHeader->manifestHash, kVoxRlManifestHashWords, sizeof(imageHeader->manifestHash)))
    {
        return Fail(VOX_RL_BLOCK_BAD_MANIFEST_HASH);
    }
    if (!VoxRlIsKnownBlockKind(imageHeader->blockKind))
    {
        return Fail(VOX_RL_BLOCK_BAD_KIND);
    }
    if (frame->messageType != static_cast<u8>(imageHeader->blockKind))
    {
        return Fail(VOX_RL_BLOCK_MESSAGE_KIND_MISMATCH);
    }
    if (VoxRlIsPipeBlockKind(imageHeader->blockKind) && frame->payloadLength > kVoxRlMaximumFramePayloadBytes)
    {
        return Fail(VOX_RL_BLOCK_BAD_PAYLOAD_LENGTH);
    }
    if (imageHeader->imageSize != frame->payloadLength || imageHeader->imageSize > kVoxRlMaximumImageBytes)
    {
        return Fail(VOX_RL_BLOCK_BAD_IMAGE_LENGTH);
    }
    u32 directoryLength = 0;
    u32 directoryEnd = 0;
    if (!VoxRlMultiplyU32(imageHeader->sectionCount, sizeof(VoxRlSectionDirectoryEntry), directoryLength) ||
        !VoxRlAddU32(static_cast<u32>(sizeof(VoxRlImageHeader)), directoryLength, directoryEnd) ||
        directoryEnd > imageHeader->imageSize)
    {
        return Fail(VOX_RL_BLOCK_BAD_DIRECTORY);
    }
    const VoxRlSectionDirectoryEntry* directory = reinterpret_cast<const VoxRlSectionDirectoryEntry*>(image + sizeof(VoxRlImageHeader));
    u16 lastKind = 0;
    u16 lastOrder = 0;
    u32 lastEnd = directoryEnd;
    for (u16 index = 0; index < imageHeader->sectionCount; ++index)
    {
        const VoxRlSectionDirectoryEntry& entry = directory[index];
        if (entry.kind == 0 || entry.reserved != 0)
        {
            return Fail(VOX_RL_BLOCK_BAD_DIRECTORY);
        }
        if ((entry.offset & (kVoxRlAlignment - 1)) != 0 || entry.offset < directoryEnd)
        {
            return Fail(VOX_RL_BLOCK_SECTION_ALIGNMENT);
        }
        if (!VoxRlIsImageRange(entry.offset, entry.byteLength, imageHeader->imageSize) || entry.offset < lastEnd)
        {
            return Fail(VOX_RL_BLOCK_SECTION_LENGTH);
        }
        if (entry.kind <= lastKind)
        {
            return Fail(VOX_RL_BLOCK_DUPLICATE_SECTION);
        }
        const VoxRlSectionDefinition* definition = VoxRlFindSectionDefinition(entry.kind);
        if (definition != 0)
        {
            if (definition->blockKind != imageHeader->blockKind)
            {
                return Fail(VOX_RL_BLOCK_SECTION_KIND_MISMATCH);
            }
            if (definition->canonicalOrder <= lastOrder)
            {
                return Fail(VOX_RL_BLOCK_SECTION_ORDER);
            }
            if (!VoxRlHasValidSectionCount(*definition, entry, options))
            {
                return Fail(VOX_RL_BLOCK_SECTION_COUNT);
            }
            if (definition->recordSize != 0)
            {
                u32 expectedLength = 0;
                if (!VoxRlMultiplyU32(entry.count, definition->recordSize, expectedLength) || expectedLength != entry.byteLength)
                {
                    return Fail(VOX_RL_BLOCK_SECTION_LENGTH);
                }
            }
            lastOrder = definition->canonicalOrder;
        }
        u32 entryEnd = 0;
        if (!VoxRlAddU32(entry.offset, entry.byteLength, entryEnd))
        {
            return Fail(VOX_RL_BLOCK_SECTION_LENGTH);
        }
        lastEnd = entryEnd;
        lastKind = entry.kind;
    }
    if (lastEnd != imageHeader->imageSize)
    {
        return Fail(VOX_RL_BLOCK_BAD_IMAGE_LENGTH);
    }
    if (!VoxRlHasRequiredSections(directory, imageHeader->sectionCount, imageHeader->blockKind))
    {
        return Fail(VOX_RL_BLOCK_REQUIRED_SECTION_MISSING);
    }
    if (!VoxRlValidatePortableBools(image, directory, imageHeader->sectionCount))
    {
        return Fail(VOX_RL_BLOCK_BAD_PORTABLE_BOOL);
    }
    if (!VoxRlValidateRanges(image, directory, imageHeader->sectionCount))
    {
        return Fail(VOX_RL_BLOCK_BAD_RANGE);
    }
    if (!VoxRlValidateStableIds(image, directory, imageHeader->sectionCount))
    {
        return Fail(VOX_RL_BLOCK_BAD_RANGE);
    }
    if (options != 0)
    {
        if (options->checkSession &&
            (imageHeader->sessionLow != options->sessionLow || imageHeader->sessionHigh != options->sessionHigh))
        {
            return Fail(VOX_RL_BLOCK_BAD_SESSION);
        }
        if (options->checkTurn && imageHeader->turn != options->turn)
        {
            return Fail(VOX_RL_BLOCK_BAD_TURN);
        }
        if (options->checkPlayer && imageHeader->player != options->player)
        {
            return Fail(VOX_RL_BLOCK_BAD_PLAYER);
        }
        if (options->checkGeneration && imageHeader->generation != options->generation)
        {
            return Fail(VOX_RL_BLOCK_BAD_GENERATION);
        }
        if (options->checkStaticGeneration && imageHeader->staticGeneration != options->staticGeneration)
        {
            return Fail(VOX_RL_BLOCK_BAD_STATIC_GENERATION);
        }
        if (options->checkWorldGeneration && imageHeader->worldGeneration != options->worldGeneration)
        {
            return Fail(VOX_RL_BLOCK_BAD_WORLD_GENERATION);
        }
        if (options->checkCampaignGeneration && imageHeader->campaignGeneration != options->campaignGeneration)
        {
            return Fail(VOX_RL_BLOCK_BAD_CAMPAIGN_GENERATION);
        }
        if (options->checkDeltaSequence && imageHeader->deltaSequence != options->deltaSequence)
        {
            return Fail(VOX_RL_BLOCK_BAD_DELTA_SEQUENCE);
        }
    }
    bytes_ = bytes;
    byteLength_ = completeLength;
    frameHeader_ = frame;
    imageHeader_ = imageHeader;
    directory_ = directory;
    status_ = VOX_RL_BLOCK_OK;
    return true;
}

// Returns the status from the latest validation attempt.
VoxRlBlockStatus VoxRlBlockView::Status() const
{
    return status_;
}

// Returns whether this view has a validated backing block.
bool VoxRlBlockView::IsValid() const
{
    return bytes_ != 0;
}

// Returns the validated framed byte pointer.
const u8* VoxRlBlockView::Bytes() const
{
    return bytes_;
}

// Returns the validated framed byte count.
u32 VoxRlBlockView::ByteLength() const
{
    return byteLength_;
}

// Returns the validated frame header.
const VoxRlFrameHeader* VoxRlBlockView::FrameHeader() const
{
    return frameHeader_;
}

// Returns the validated image header.
const VoxRlImageHeader* VoxRlBlockView::ImageHeader() const
{
    return imageHeader_;
}

// Returns one validated directory entry by section kind.
const VoxRlSectionDirectoryEntry* VoxRlBlockView::FindSection(u16 sectionKind) const
{
    if (!IsValid())
    {
        return 0;
    }
    return VoxRlFindDirectoryEntry(directory_, imageHeader_->sectionCount, sectionKind);
}

// Returns the first byte of one validated section.
const u8* VoxRlBlockView::SectionBytes(u16 sectionKind) const
{
    const VoxRlSectionDirectoryEntry* entry = FindSection(sectionKind);
    if (entry == 0)
    {
        return 0;
    }
    return bytes_ + sizeof(VoxRlFrameHeader) + entry->offset;
}

// Converts validation statuses to short diagnostics without allocating memory.
const char* VoxRlBlockStatusName(VoxRlBlockStatus status)
{
    static const char* const names[] = {
        "ok", "null bytes", "unaligned bytes", "truncated frame", "bad magic", "bad protocol version",
        "bad payload length", "truncated image", "bad schema version", "bad manifest hash", "bad block kind",
        "message kind mismatch", "bad image length", "bad directory", "unknown section", "section kind mismatch",
        "section order", "section alignment", "section length", "section count", "duplicate section", "required section missing",
        "bad portable bool", "bad range", "bad session", "bad turn", "bad player", "bad generation", "bad static generation",
        "bad world generation", "bad campaign generation", "bad delta sequence", "bad layout"
    };
    const u32 count = static_cast<u32>(sizeof(names) / sizeof(names[0]));
    if (static_cast<u32>(status) >= count)
    {
        return "unknown block status";
    }
    return names[status];
}
