// Generated by simulator/schema/generate_schema.py. Do not edit.
// Manifest hash: 56f68d7daee3e4ebf47881a8b686080524741337177448d6ef95a88c424e809f

#ifndef VOX_RL_COLLECTORS_GENERATED_H
#define VOX_RL_COLLECTORS_GENERATED_H

#include "VoxRlSchema.generated.h"

bool CollectStaticRulesRecord(StaticRulesRecord& out);
bool CollectStaticHandicapLimitsRecord(StaticHandicapLimitsRecord& out);
bool CollectTerrainInfoRecord(CvTerrainInfo& terrainInfo, TerrainInfoRecord& out);
bool CollectFeatureInfoRecord(CvFeatureInfo& featureInfo, FeatureInfoRecord& out);
bool CollectRouteInfoRecord(CvRouteInfo& routeInfo, RouteInfoRecord& out);
bool CollectImprovementInfoRecord(CvImprovementEntry& improvementInfo, ImprovementInfoRecord& out);
bool CollectResourceInfoRecord(CvResourceInfo& resourceInfo, ResourceInfoRecord& out);
bool CollectUnitEntryInfoRecord(CvUnitEntry& unitEntry, UnitEntryInfoRecord& out);
bool CollectStaticBuildIdsRecord(StaticBuildIdsRecord& out);
bool CollectMapTopologyRecord(CvMap& map, MapTopologyRecord& out);
bool CollectPlotTopologyRecord(CvPlot& plot, PlotTopologyRecord& out);
bool CollectPlotDynamicRecord(CvPlot& plot, PlotDynamicRecord& out);
bool CollectPlotTeamRecord(TeamTypes otherTeam, PlotTeamRecord& out);
bool CollectRevealedOverrideRecord(CvPlot& plot, TeamTypes otherTeam, RevealedOverrideRecord& out);
bool CollectUnitRecord(CvUnit& unit, TeamTypes capturingTeam, UnitRecord& out);
bool CollectCityRecord(CvCity& city, PlayerTypes capturingPlayer, CityRecord& out);
bool CollectTeamRelationRecord(CvTeam& team, TeamTypes otherTeam, PlayerTypes capturingPlayer, TeamRelationRecord& out);
bool CollectTeamRecord(CvTeam& team, TeamRecord& out);
bool CollectPlayerRecord(CvPlayer& player, PlayerTypes otherPlayer, PlayerRecord& out);
bool CollectMinorRelationRecord(CvPlayer& player, CvMinorCivAI& minorCivAI, PlayerTypes otherPlayer, PlayerTypes queriedPlayer, MinorRelationRecord& out);
bool CollectZoneRecord(CvTacticalDominanceZone& zone, ZoneRecord& out);
bool CollectZoneNeighborRecord(ZoneNeighborRecord& out);
bool CollectDangerPlayerRecord(PlayerTypes otherPlayer, DangerPlayerRecord& out);
bool CollectKnownAttackerRecord(KnownAttackerRecord& out);
bool CollectVanishedAttackerRecord(VanishedAttackerRecord& out);
bool CollectCampaignHeaderRecord(CvMilitaryAI& campaign, CvPlayer& player, CampaignHeaderRecord& out);
bool CollectCampaignEnemyRecord(CampaignEnemyRecord& out);
bool CollectCampaignAttackTargetRecord(CampaignAttackTargetRecord& out);
bool CollectCampaignExposedCityRecord(CampaignExposedCityRecord& out);
bool CollectCampaignOperationRecord(CampaignOperationRecord& out);
bool CollectCampaignOperationArmyIdRecord(CampaignOperationArmyIdRecord& out);
bool CollectCampaignArmyRecord(CampaignArmyRecord& out);
bool CollectCampaignFormationEntryRecord(CampaignFormationEntryRecord& out);
bool CollectCampaignThreatenedCityRecord(CampaignThreatenedCityRecord& out);
bool CollectCampaignCoastalThreatenedCityRecord(CampaignCoastalThreatenedCityRecord& out);
bool CollectCampaignZoneRecord(CvTacticalDominanceZone& zone, CampaignZoneRecord& out);
bool CollectCampaignZoneNeighborRecord(CampaignZoneNeighborRecord& out);
bool CollectRequestHeaderRecord(RequestHeaderRecord& out);
bool CollectRequestDeltaUnitRecord(RequestDeltaUnitRecord& out);
bool CollectRequestDeltaPlotRecord(RequestDeltaPlotRecord& out);
bool CollectRequestDeltaCityRecord(RequestDeltaCityRecord& out);
bool CollectRequestRemovedUnitRecord(RequestRemovedUnitRecord& out);
bool CollectRequestKnownAttackerRecord(RequestKnownAttackerRecord& out);
bool CollectRequestParticipantRecord(RequestParticipantRecord& out);
bool CollectRequestDroppedUnitRecord(RequestDroppedUnitRecord& out);
bool CollectResultAssignmentRecord(ResultAssignmentRecord& out);
bool CollectResultReachabilityStartRecord(ResultReachabilityStartRecord& out);
bool CollectResultReachabilityMoveRecord(ResultReachabilityMoveRecord& out);
bool CollectResultFreedPlotRecord(ResultFreedPlotRecord& out);
bool CollectResultDangerEvidenceRecord(ResultDangerEvidenceRecord& out);
bool CollectResultDangerUnitEvidenceRecord(ResultDangerUnitEvidenceRecord& out);
bool CollectResultDangerCityEvidenceRecord(ResultDangerCityEvidenceRecord& out);
bool CollectResultDangerCaptureEvidenceRecord(ResultDangerCaptureEvidenceRecord& out);
bool CollectResultOracleEvidenceRecord(ResultOracleEvidenceRecord& out);
bool CollectResultMetadataRecord(ResultMetadataRecord& out);
bool CollectResultAssignmentDamageRecord(ResultAssignmentDamageRecord& out);
bool CollectResultAssignmentHealingRecord(ResultAssignmentHealingRecord& out);
bool CollectPlotPassabilityRecord(CvPlot& plot, PlotPassabilityRecord& out);
bool CollectInterceptorCacheRecord(InterceptorCacheRecord& out);
bool CollectInterceptorCacheEntryRecord(InterceptorCacheEntryRecord& out);
bool CollectCitadelPlotRecord(CitadelPlotRecord& out);
bool CollectRequestRemovedCityRecord(RequestRemovedCityRecord& out);
bool CollectRequestPlotPassabilityRecord(RequestPlotPassabilityRecord& out);
bool CollectRequestVisibilityFlipRecord(RequestVisibilityFlipRecord& out);
bool CollectRequestRevealedOverrideUpsertRecord(RequestRevealedOverrideUpsertRecord& out);
bool CollectRequestRemovedRevealedOverrideRecord(RequestRemovedRevealedOverrideRecord& out);
bool CollectRequestInterceptorReplacementRecord(RequestInterceptorReplacementRecord& out);
bool CollectRequestInterceptorEntryRecord(RequestInterceptorEntryRecord& out);
bool CollectRequestUnitStrengthRecord(RequestUnitStrengthRecord& out);
bool CollectRequestCityStrengthRecord(RequestCityStrengthRecord& out);
bool CollectStaticUnitClassInfoRecord(StaticUnitClassInfoRecord& out);
bool CollectRequestSplashDamageRecord(RequestSplashDamageRecord& out);
bool CollectRequestPlagueDamageRecord(RequestPlagueDamageRecord& out);
bool CollectRequestDangerEventRecord(RequestDangerEventRecord& out);
bool CollectRequestTeamRelationRecord(RequestTeamRelationRecord& out);
bool CollectReplayHeaderRecord(ReplayHeaderRecord& out);
bool CollectReplayAssignmentRecord(ReplayAssignmentRecord& out);
bool CollectReplayAssignmentDamageRecord(ReplayAssignmentDamageRecord& out);
bool CollectReplayAssignmentHealingRecord(ReplayAssignmentHealingRecord& out);
bool CollectReplayUnusableUnitRecord(ReplayUnusableUnitRecord& out);

#endif
