// Generated by simulator/schema/generate_schema.py. Do not edit.
// Manifest hash: c900e33092838146694ee9d797653e4f00ec45116f38784a5a4142d5e4fdff1e
#ifndef VOX_RL_BLOCK_STORAGE_H
#define VOX_RL_BLOCK_STORAGE_H

#include <vector>

#include "VoxRlTypes.h"

// Keeps borrowed read-only bytes alive only while an external owner remains valid.
class VoxRlBorrowedBlockStorage {
public:
    // Creates an empty borrowed storage view.
    VoxRlBorrowedBlockStorage();

    // Borrows one aligned read-only block without copying it.
    bool Reset(const void* bytes, u32 byteLength);

    // Clears the borrowed byte range before the external owner is released.
    void Clear();

    // Returns the borrowed bytes.
    const u8* Bytes() const;

    // Returns the borrowed byte count.
    u32 ByteLength() const;

private:
    const u8* bytes_;
    u32 byteLength_;
};

// Owns a mutable byte allocation used for copied fixture and pipe blocks.
class VoxRlOwnedBlockStorage {
public:
    // Creates empty owned storage.
    VoxRlOwnedBlockStorage();

    // Resizes the owned byte allocation and clears the new block deterministically.
    bool Allocate(u32 byteLength);

    // Clears the owned bytes.
    void Clear();

    // Returns writable owned bytes, or zero for an empty allocation.
    u8* MutableBytes();

    // Returns read-only owned bytes, or zero for an empty allocation.
    const u8* Bytes() const;

    // Returns the owned byte count.
    u32 ByteLength() const;

private:
    // Disallows accidental copies of storage that owns a mutable byte allocation.
    VoxRlOwnedBlockStorage(const VoxRlOwnedBlockStorage& other);

    // Disallows accidental assignment of storage that owns a mutable byte allocation.
    VoxRlOwnedBlockStorage& operator=(const VoxRlOwnedBlockStorage& other);

    std::vector<u8> bytes_;
};

// Owns a read-only Windows fixture-file mapping for the lifetime of a block view.
class VoxRlFixtureFileMapping {
public:
    // Creates an unopened fixture mapping.
    VoxRlFixtureFileMapping();

    // Closes the mapping and its file handles.
    ~VoxRlFixtureFileMapping();

    // Opens an exact read-only fixture mapping from a UTF-16 filesystem path.
    bool Open(const wchar_t* path);

    // Closes the mapping and its backing handles.
    void Close();

    // Returns the mapped read-only bytes, or zero when no file is open.
    const u8* Bytes() const;

    // Returns the mapped byte count, or zero when no file is open.
    u32 ByteLength() const;

private:
    // Disallows accidental copies of storage that owns Windows handles and a mapped view.
    VoxRlFixtureFileMapping(const VoxRlFixtureFileMapping& other);

    // Disallows accidental assignment of storage that owns Windows handles and a mapped view.
    VoxRlFixtureFileMapping& operator=(const VoxRlFixtureFileMapping& other);

    void* fileHandle_;
    void* mappingHandle_;
    const u8* bytes_;
    u32 byteLength_;
};

#endif
