// Generated by simulator/schema/generate_schema.py. Do not edit.
// Manifest hash: c900e33092838146694ee9d797653e4f00ec45116f38784a5a4142d5e4fdff1e
#ifndef VOX_RL_TYPES_H
#define VOX_RL_TYPES_H

#include <stddef.h>

typedef signed char i8;
typedef unsigned char u8;
typedef signed short i16;
typedef unsigned short u16;
typedef signed int i32;
typedef unsigned int u32;
typedef unsigned long long VoxRlWideSize;

enum { kVoxRlAlignment = 4 };

// Returns whether adding two serialized lengths fits in a u32 result.
inline bool VoxRlAddU32(u32 left, u32 right, u32& result)
{
    const VoxRlWideSize total = static_cast<VoxRlWideSize>(left) + static_cast<VoxRlWideSize>(right);
    if (total > 0xffffffffULL)
    {
        return false;
    }
    result = static_cast<u32>(total);
    return true;
}

// Returns whether multiplying two serialized lengths fits in a u32 result.
inline bool VoxRlMultiplyU32(u32 left, u32 right, u32& result)
{
    const VoxRlWideSize total = static_cast<VoxRlWideSize>(left) * static_cast<VoxRlWideSize>(right);
    if (total > 0xffffffffULL)
    {
        return false;
    }
    result = static_cast<u32>(total);
    return true;
}

// Rounds a serialized offset up to the portable record alignment.
inline bool VoxRlAlignU32(u32 value, u32& result)
{
    u32 padded = 0;
    if (!VoxRlAddU32(value, kVoxRlAlignment - 1, padded))
    {
        return false;
    }
    result = padded & ~(static_cast<u32>(kVoxRlAlignment) - 1U);
    return true;
}

// Compares two byte sequences without relying on a platform library routine.
inline bool VoxRlBytesEqual(const void* left, const void* right, u32 length)
{
    const u8* leftBytes = static_cast<const u8*>(left);
    const u8* rightBytes = static_cast<const u8*>(right);
    for (u32 index = 0; index < length; ++index)
    {
        if (leftBytes[index] != rightBytes[index])
        {
            return false;
        }
    }
    return true;
}

// Clears a byte sequence deterministically before a builder writes its records.
inline void VoxRlZeroBytes(void* destination, u32 length)
{
    u8* bytes = static_cast<u8*>(destination);
    for (u32 index = 0; index < length; ++index)
    {
        bytes[index] = 0;
    }
}

// Reads an unaligned little-endian u32 from portable image bytes.
inline u32 VoxRlReadU32(const void* source)
{
    const u8* bytes = static_cast<const u8*>(source);
    return static_cast<u32>(bytes[0]) |
        (static_cast<u32>(bytes[1]) << 8) |
        (static_cast<u32>(bytes[2]) << 16) |
        (static_cast<u32>(bytes[3]) << 24);
}

#endif
