// Generated by simulator/schema/generate_schema.py. Do not edit.
// Manifest hash: 993c8f662459739744eb888c365cc635aaf69b7d3a7065677ca74b1c86f6fc4b

#ifndef VOX_RL_COLLECTORS_GENERATED_H
#define VOX_RL_COLLECTORS_GENERATED_H

#include "VoxRlSchema.generated.h"

bool CollectStaticRulesRecord(StaticRulesRecord& out);
bool CollectStaticHandicapLimitsRecord(StaticHandicapLimitsRecord& out);
bool CollectTerrainInfoRecord(CvTerrainInfo& terrainInfo, TerrainInfoRecord& out);
bool CollectFeatureInfoRecord(CvFeatureInfo& featureInfo, FeatureInfoRecord& out);
bool CollectRouteInfoRecord(CvRouteInfo& routeInfo, RouteInfoRecord& out);
bool CollectImprovementInfoRecord(CvImprovementEntry& improvementInfo, ImprovementInfoRecord& out);
bool CollectResourceInfoRecord(CvResourceInfo& resourceInfo, ResourceInfoRecord& out);
bool CollectUnitEntryInfoRecord(CvUnitEntry& unitEntry, UnitEntryInfoRecord& out);
bool CollectStaticBuildIdsRecord(StaticBuildIdsRecord& out);
bool CollectMapTopologyRecord(CvMap& map, MapTopologyRecord& out);
bool CollectPlotTopologyRecord(CvPlot& plot, PlotTopologyRecord& out);
bool CollectPromotionInfoRecord(CvPromotionEntry& promotionInfo, PromotionInfoRecord& out);
bool CollectProcessInfoRecord(CvProcessInfo& processInfo, ProcessInfoRecord& out);
bool CollectCityEventChoiceInfoRecord(CvModEventCityChoiceInfo& cityEventChoiceInfo, CityEventChoiceInfoRecord& out);
bool CollectPlotCoreRecord(CvPlot& plot, PlotCoreRecord& out);
bool CollectPlotTeamRecord(TeamTypes otherTeam, PlotTeamRecord& out);
bool CollectRevealedOverrideRecord(CvPlot& plot, TeamTypes otherTeam, RevealedOverrideRecord& out);
bool CollectUnitRecord(CvUnit& unit, TeamTypes capturingTeam, UnitRecord& out);
bool CollectCityRecord(CvCity& city, PlayerTypes capturingPlayer, CityRecord& out);
bool CollectTeamRelationRecord(CvTeam& team, TeamTypes otherTeam, PlayerTypes capturingPlayer, TeamRelationRecord& out);
bool CollectTeamRecord(CvTeam& team, TeamRecord& out);
bool CollectPlayerRecord(CvPlayer& player, PlayerTypes otherPlayer, PlayerRecord& out);
bool CollectMinorRelationRecord(CvPlayer& player, CvMinorCivAI& minorCivAI, PlayerTypes otherPlayer, PlayerTypes queriedPlayer, MinorRelationRecord& out);
bool CollectZoneRecord(const CvTacticalDominanceZone& zone, ZoneRecord& out);
bool CollectZoneNeighborRecord(ZoneNeighborRecord& out);
bool CollectDangerPlayerRecord(PlayerTypes otherPlayer, DangerPlayerRecord& out);
bool CollectKnownAttackerRecord(KnownAttackerRecord& out);
bool CollectVanishedAttackerRecord(VanishedAttackerRecord& out);
bool CollectCampaignHeaderRecord(CvMilitaryAI& campaign, CvPlayer& player, CampaignHeaderRecord& out);
bool CollectCampaignEnemyRecord(CampaignEnemyRecord& out);
bool CollectCampaignAttackTargetRecord(CampaignAttackTargetRecord& out);
bool CollectCampaignExposedCityRecord(CampaignExposedCityRecord& out);
bool CollectCampaignOperationRecord(CampaignOperationRecord& out);
bool CollectCampaignOperationArmyIdRecord(CampaignOperationArmyIdRecord& out);
bool CollectCampaignArmyRecord(CampaignArmyRecord& out);
bool CollectCampaignFormationEntryRecord(CampaignFormationEntryRecord& out);
bool CollectCampaignThreatenedCityRecord(CampaignThreatenedCityRecord& out);
bool CollectCampaignCoastalThreatenedCityRecord(CampaignCoastalThreatenedCityRecord& out);
bool CollectCampaignZoneRecord(const CvTacticalDominanceZone& zone, CampaignZoneRecord& out);
bool CollectCampaignZoneNeighborRecord(CampaignZoneNeighborRecord& out);
bool CollectRequestHeaderRecord(RequestHeaderRecord& out);
bool CollectRequestDeltaUnitRecord(RequestDeltaUnitRecord& out);
bool CollectRequestDeltaPlotCoreRecord(RequestDeltaPlotCoreRecord& out);
bool CollectRequestDeltaCityRecord(RequestDeltaCityRecord& out);
bool CollectRequestRemovedUnitRecord(RequestRemovedUnitRecord& out);
bool CollectRequestKnownAttackerRecord(RequestKnownAttackerRecord& out);
bool CollectRequestParticipantRecord(RequestParticipantRecord& out);
bool CollectRequestDroppedUnitRecord(RequestDroppedUnitRecord& out);
bool CollectResultAssignmentRecord(ResultAssignmentRecord& out);
bool CollectResultAssignmentDamageRecord(ResultAssignmentDamageRecord& out);
bool CollectResultAssignmentHealingRecord(ResultAssignmentHealingRecord& out);
bool CollectTeamPassabilityRecord(TeamPassabilityRecord& out);
bool CollectInterceptorCacheRecord(InterceptorCacheRecord& out);
bool CollectInterceptorCacheEntryRecord(InterceptorCacheEntryRecord& out);
bool CollectCitadelPlotRecord(CitadelPlotRecord& out);
bool CollectRequestRemovedCityRecord(RequestRemovedCityRecord& out);
bool CollectRequestTeamPassabilityRecord(RequestTeamPassabilityRecord& out);
bool CollectRequestVisibilityFlipRecord(RequestVisibilityFlipRecord& out);
bool CollectRequestRevealedOverrideUpsertRecord(RequestRevealedOverrideUpsertRecord& out);
bool CollectRequestRemovedRevealedOverrideRecord(RequestRemovedRevealedOverrideRecord& out);
bool CollectRequestInterceptorReplacementRecord(RequestInterceptorReplacementRecord& out);
bool CollectRequestInterceptorEntryRecord(RequestInterceptorEntryRecord& out);
bool CollectStaticUnitClassInfoRecord(int unitClassIndex, StaticUnitClassInfoRecord& out);
bool CollectRequestDangerEventRecord(RequestDangerEventRecord& out);
bool CollectRequestTeamRelationRecord(RequestTeamRelationRecord& out);
bool CollectReplayHeaderRecord(ReplayHeaderRecord& out);
bool CollectReplayAssignmentRecord(ReplayAssignmentRecord& out);
bool CollectReplayAssignmentDamageRecord(ReplayAssignmentDamageRecord& out);
bool CollectReplayAssignmentHealingRecord(ReplayAssignmentHealingRecord& out);
bool CollectReplayUnusableUnitRecord(ReplayUnusableUnitRecord& out);
bool CollectUnitModifierRecord(UnitModifierRecord& out);
bool CollectUnitPlagueRecord(UnitPlagueRecord& out);
bool CollectUnitBlockedPromotionRecord(UnitBlockedPromotionRecord& out);
bool CollectUnitAttackCountRecord(UnitAttackCountRecord& out);
bool CollectPlayerResistanceRecord(PlayerResistanceRecord& out);
bool CollectCityAttackCountRecord(CityAttackCountRecord& out);
bool CollectRequestUnitModifierRecord(RequestUnitModifierRecord& out);
bool CollectRequestUnitPlagueRecord(RequestUnitPlagueRecord& out);
bool CollectRequestUnitBlockedPromotionRecord(RequestUnitBlockedPromotionRecord& out);
bool CollectRequestUnitAttackCountRecord(RequestUnitAttackCountRecord& out);
bool CollectRequestPlayerResistanceRecord(RequestPlayerResistanceRecord& out);
bool CollectRequestCityAttackCountRecord(RequestCityAttackCountRecord& out);
bool CollectRequestZoneReplacementRecord(RequestZoneReplacementRecord& out);
bool CollectRequestZoneNeighborRecord(RequestZoneNeighborRecord& out);
bool CollectPlotZoneIndexRecord(PlotZoneIndexRecord& out);
bool CollectPlotZoneIndexWideRecord(PlotZoneIndexWideRecord& out);
bool CollectRequestDeltaPlotZoneRecord(RequestDeltaPlotZoneRecord& out);
bool CollectRequestDeltaPlotZoneWideRecord(RequestDeltaPlotZoneWideRecord& out);
bool CollectUnitMovementCountRecord(UnitMovementCountRecord& out);
bool CollectRequestUnitMovementCountRecord(RequestUnitMovementCountRecord& out);

#endif
