// Generated by simulator/schema/generate_schema.py. Do not edit.
// Manifest hash: da55dcd5ae2b13096772ec0d6b4e3245458ed86301f7ad87340021a2ba9cf781

#ifndef VOX_RL_COLLECTORS_GENERATED_H
#define VOX_RL_COLLECTORS_GENERATED_H

#include "VoxRlSchema.generated.h"

// Reports one capture conversion the manifest bounds rejected. The DLL capture
// runtime defines this hook; the collectors compile only inside the DLL.
void VoxRlNoteCaptureRangeFailure(const char* reason, const char* record, const char* field, i32 value, i32 minValue, i32 maxValue);

bool CollectStaticRulesRecord(StaticRulesRecord& out);
bool CollectStaticHandicapLimitsRecord(StaticHandicapLimitsRecord& out);
bool CollectTerrainInfoRecord(CvTerrainInfo& terrainInfo, TerrainInfoRecord& out);
bool CollectFeatureInfoRecord(CvFeatureInfo& featureInfo, FeatureInfoRecord& out);
bool CollectRouteInfoRecord(CvRouteInfo& routeInfo, RouteInfoRecord& out);
bool CollectImprovementInfoRecord(CvImprovementEntry& improvementInfo, ImprovementInfoRecord& out);
bool CollectResourceInfoRecord(CvResourceInfo& resourceInfo, ResourceInfoRecord& out);
bool CollectUnitEntryInfoRecord(CvUnitEntry& unitEntry, UnitEntryInfoRecord& out);
bool CollectStaticBuildIdsRecord(StaticBuildIdsRecord& out);
bool CollectMapTopologyRecord(CvMap& map, MapTopologyRecord& out);
bool CollectPlotTopologyRecord(CvPlot& plot, PlotTopologyRecord& out);
bool CollectPromotionInfoRecord(CvPromotionEntry& promotionInfo, PromotionInfoRecord& out);
bool CollectProcessInfoRecord(CvProcessInfo& processInfo, ProcessInfoRecord& out);
bool CollectCityEventChoiceInfoRecord(CvModEventCityChoiceInfo& cityEventChoiceInfo, CityEventChoiceInfoRecord& out);
bool CollectPlotTeamRecord(TeamTypes otherTeam, PlotTeamRecord& out);
bool CollectRevealedOverrideRecord(CvPlot& plot, TeamTypes otherTeam, RevealedOverrideRecord& out);
bool CollectCityRecord(CvCity& city, PlayerTypes capturingPlayer, CityRecord& out);
bool CollectTeamRelationRecord(CvTeam& team, TeamTypes otherTeam, PlayerTypes capturingPlayer, TeamRelationRecord& out);
bool CollectTeamRecord(CvTeam& team, TeamRecord& out);
bool CollectPlayerRecord(CvPlayer& player, PlayerTypes otherPlayer, PlayerRecord& out);
bool CollectMinorRelationRecord(CvPlayer& player, CvMinorCivAI& minorCivAI, PlayerTypes otherPlayer, PlayerTypes queriedPlayer, MinorRelationRecord& out);
bool CollectZoneRecord(const CvTacticalDominanceZone& zone, ZoneRecord& out);
bool CollectZoneNeighborRecord(ZoneNeighborRecord& out);
bool CollectDangerPlayerRecord(PlayerTypes otherPlayer, DangerPlayerRecord& out);
bool CollectKnownAttackerRecord(KnownAttackerRecord& out);
bool CollectVanishedAttackerRecord(VanishedAttackerRecord& out);
bool CollectCampaignHeaderRecord(CvMilitaryAI& campaign, CvPlayer& player, CampaignHeaderRecord& out);
bool CollectCampaignEnemyRecord(CampaignEnemyRecord& out);
bool CollectCampaignAttackTargetRecord(CampaignAttackTargetRecord& out);
bool CollectCampaignExposedCityRecord(CampaignExposedCityRecord& out);
bool CollectCampaignOperationRecord(CampaignOperationRecord& out);
bool CollectCampaignOperationArmyIdRecord(CampaignOperationArmyIdRecord& out);
bool CollectCampaignArmyRecord(CampaignArmyRecord& out);
bool CollectCampaignFormationEntryRecord(CampaignFormationEntryRecord& out);
bool CollectCampaignThreatenedCityRecord(CampaignThreatenedCityRecord& out);
bool CollectCampaignCoastalThreatenedCityRecord(CampaignCoastalThreatenedCityRecord& out);
bool CollectCampaignZoneRecord(const CvTacticalDominanceZone& zone, CampaignZoneRecord& out);
bool CollectCampaignZoneNeighborRecord(CampaignZoneNeighborRecord& out);
bool CollectRequestHeaderRecord(RequestHeaderRecord& out);
bool CollectRequestDeltaUnitRecord(RequestDeltaUnitRecord& out);
bool CollectRequestDeltaPlotCoreRecord(RequestDeltaPlotCoreRecord& out);
bool CollectRequestDeltaCityRecord(RequestDeltaCityRecord& out);
bool CollectRequestRemovedUnitRecord(RequestRemovedUnitRecord& out);
bool CollectRequestKnownAttackerRecord(RequestKnownAttackerRecord& out);
bool CollectRequestParticipantRecord(RequestParticipantRecord& out);
bool CollectRequestDroppedUnitRecord(RequestDroppedUnitRecord& out);
bool CollectResultAssignmentRecord(ResultAssignmentRecord& out);
bool CollectResultAssignmentDamageRecord(ResultAssignmentDamageRecord& out);
bool CollectResultAssignmentHealingRecord(ResultAssignmentHealingRecord& out);
bool CollectTeamPassabilityRecord(TeamPassabilityRecord& out);
bool CollectInterceptorCacheRecord(InterceptorCacheRecord& out);
bool CollectInterceptorCacheEntryRecord(InterceptorCacheEntryRecord& out);
bool CollectRequestRemovedCityRecord(RequestRemovedCityRecord& out);
bool CollectRequestTeamPassabilityRecord(RequestTeamPassabilityRecord& out);
bool CollectRequestVisibilityWordRecord(RequestVisibilityWordRecord& out);
bool CollectRequestRevealedOverrideUpsertRecord(RequestRevealedOverrideUpsertRecord& out);
bool CollectRequestRemovedRevealedOverrideRecord(RequestRemovedRevealedOverrideRecord& out);
bool CollectRequestInterceptorReplacementRecord(RequestInterceptorReplacementRecord& out);
bool CollectRequestInterceptorEntryRecord(RequestInterceptorEntryRecord& out);
bool CollectStaticUnitClassInfoRecord(int unitClassIndex, StaticUnitClassInfoRecord& out);
bool CollectRequestDangerEventRecord(RequestDangerEventRecord& out);
bool CollectRequestTeamRelationRecord(RequestTeamRelationRecord& out);
bool CollectReplayHeaderRecord(ReplayHeaderRecord& out);
bool CollectReplayAssignmentRecord(ReplayAssignmentRecord& out);
bool CollectReplayAssignmentDamageRecord(ReplayAssignmentDamageRecord& out);
bool CollectReplayAssignmentHealingRecord(ReplayAssignmentHealingRecord& out);
bool CollectReplayUnusableUnitRecord(ReplayUnusableUnitRecord& out);
bool CollectUnitModifierRecord(UnitModifierRecord& out);
bool CollectUnitPlagueRecord(UnitPlagueRecord& out);
bool CollectUnitBlockedPromotionRecord(UnitBlockedPromotionRecord& out);
bool CollectUnitAttackCountRecord(UnitAttackCountRecord& out);
bool CollectPlayerResistanceRecord(PlayerResistanceRecord& out);
bool CollectCityAttackCountRecord(CityAttackCountRecord& out);
bool CollectRequestZoneReplacementRecord(RequestZoneReplacementRecord& out);
bool CollectRequestZoneNeighborRecord(RequestZoneNeighborRecord& out);
bool CollectPlotZoneIndexRecord(PlotZoneIndexRecord& out);
bool CollectPlotZoneIndexWideRecord(PlotZoneIndexWideRecord& out);
bool CollectRequestDeltaPlotZoneRecord(RequestDeltaPlotZoneRecord& out);
bool CollectRequestDeltaPlotZoneWideRecord(RequestDeltaPlotZoneWideRecord& out);
bool CollectUnitMovementCountRecord(UnitMovementCountRecord& out);
bool CollectRequestUnitMovementCountRecord(RequestUnitMovementCountRecord& out);
bool CollectRequestUnitModifierReplacementRecord(RequestUnitModifierReplacementRecord& out);
bool CollectRequestUnitModifierRowRecord(RequestUnitModifierRowRecord& out);
bool CollectRequestUnitPlagueReplacementRecord(RequestUnitPlagueReplacementRecord& out);
bool CollectRequestUnitPlagueRowRecord(RequestUnitPlagueRowRecord& out);
bool CollectRequestUnitBlockedPromotionReplacementRecord(RequestUnitBlockedPromotionReplacementRecord& out);
bool CollectRequestUnitBlockedPromotionRowRecord(RequestUnitBlockedPromotionRowRecord& out);
bool CollectRequestUnitAttackCountReplacementRecord(RequestUnitAttackCountReplacementRecord& out);
bool CollectRequestUnitAttackCountRowRecord(RequestUnitAttackCountRowRecord& out);
bool CollectRequestPlayerResistanceReplacementRecord(RequestPlayerResistanceReplacementRecord& out);
bool CollectRequestPlayerResistanceRowRecord(RequestPlayerResistanceRowRecord& out);
bool CollectRequestCityAttackCountReplacementRecord(RequestCityAttackCountReplacementRecord& out);
bool CollectRequestCityAttackCountRowRecord(RequestCityAttackCountRowRecord& out);
bool CollectRequestVisibilityResetRecord(RequestVisibilityResetRecord& out);
bool CollectUnitSparseFieldRecord(UnitSparseFieldRecord& out);
bool CollectRequestUnitSparseFieldRecord(RequestUnitSparseFieldRecord& out);
bool CollectPlotSparseCountersRecord(PlotSparseCountersRecord& out);
bool CollectCityReferenceRecord(CityReferenceRecord& out);
bool CollectRequestDeltaPlotSparseCountersRecord(RequestDeltaPlotSparseCountersRecord& out);
bool CollectRequestCityReferenceRecord(RequestCityReferenceRecord& out);
bool CollectCampaignMilitaryFlavorOverrideRecord(CampaignMilitaryFlavorOverrideRecord& out);
bool CollectPlotCaptureRecord(CvPlot& plot, PlotCaptureRecord& out);
bool CollectUnitRecord(CvUnit& unit, TeamTypes capturingTeam, UnitRecord& out);

#endif
