// Generated by simulator/schema/generate_schema.py. Do not edit.
// Manifest hash: 70a929486a62b5d5e184debd6dc179b0ce287889523fecfebc13ce67138cfb82

#include "CvGameCoreDLLPCH.h"
#include "VoxRlCollectors.generated.h"

bool CollectStaticRulesRecord(StaticRulesRecord& out)
{
    // GD_INT_GET define.
    out.aiTacticalRecruitRange = static_cast<i32>(GD_INT_GET(AI_TACTICAL_RECRUIT_RANGE));
    // GD_INT_GET define.
    out.barbarianCampImprovement = static_cast<i32>(GD_INT_GET(BARBARIAN_CAMP_IMPROVEMENT));
    // GD_INT_GET define.
    out.blockadedCityAttackModifier = static_cast<i32>(GD_INT_GET(BLOCKADED_CITY_ATTACK_MODIFIER));
    // GD_INT_GET define.
    out.cityHitPointsHealedPerTurn = static_cast<i32>(GD_INT_GET(CITY_HIT_POINTS_HEALED_PER_TURN));
    // GD_INT_GET define.
    out.cityStrengthLandUnitDivisor = static_cast<i32>(GD_INT_GET(CITY_STRENGTH_LAND_UNIT_DIVISOR));
    // GD_INT_GET define.
    out.cityStrengthNavalUnitDivisor = static_cast<i32>(GD_INT_GET(CITY_STRENGTH_NAVAL_UNIT_DIVISOR));
    // GD_INT_GET define.
    out.combatAiOffenseDamageWeight = static_cast<i32>(GD_INT_GET(COMBAT_AI_OFFENSE_DAMAGEWEIGHT));
    // GD_INT_GET define.
    out.combatAiOffenseDangerWeight = static_cast<i32>(GD_INT_GET(COMBAT_AI_OFFENSE_DANGERWEIGHT));
    // GD_INT_GET define.
    out.enemyHealRate = static_cast<i32>(GD_INT_GET(ENEMY_HEAL_RATE));
    // GD_INT_GET define.
    out.greatGeneralRange = static_cast<i32>(GD_INT_GET(GREAT_GENERAL_RANGE));
    // GD_INT_GET define.
    out.maxHitPoints = static_cast<i32>(GD_INT_GET(MAX_HIT_POINTS));
    // Fixed-point movement unit.
    out.moveDenominator = static_cast<i32>(GD_INT_GET(MOVE_DENOMINATOR));
    // GD_INT_GET define.
    out.neutralHealRate = static_cast<i32>(GD_INT_GET(NEUTRAL_HEAL_RATE));
    // GD_INT_GET define.
    out.pillageHealAmount = static_cast<i32>(GD_INT_GET(PILLAGE_HEAL_AMOUNT));
    // GD_INT_GET define.
    out.plotVisibilityRange = static_cast<i32>(GD_INT_GET(PLOT_VISIBILITY_RANGE));
    // GD_INT_GET define.
    out.sappedCityAttackModifier = static_cast<i32>(GD_INT_GET(SAPPED_CITY_ATTACK_MODIFIER));
    // GD_INT_GET define.
    out.hillsExtraMovement = static_cast<i32>(GD_INT_GET(HILLS_EXTRA_MOVEMENT));
    // GD_INT_GET define.
    out.riverExtraMovement = static_cast<i32>(GD_INT_GET(RIVER_EXTRA_MOVEMENT));
    // GD_INT_GET define.
    out.airSweepInterceptionDamageMod = static_cast<i32>(GD_INT_GET(AIR_SWEEP_INTERCEPTION_DAMAGE_MOD));
    // GD_INT_GET define.
    out.amphibAttackModifier = static_cast<i32>(GD_INT_GET(AMPHIB_ATTACK_MODIFIER));
    // Pathfinder cost input.
    out.influenceHillCost = static_cast<i32>(GD_INT_GET(INFLUENCE_HILL_COST));
    // Pathfinder cost input.
    out.influenceMountainCost = static_cast<i32>(GD_INT_GET(INFLUENCE_MOUNTAIN_COST));
    // Pathfinder cost input.
    out.influenceRiverCost = static_cast<i32>(GD_INT_GET(INFLUENCE_RIVER_COST));
    // Pathfinder cost input.
    out.pathDamageWeight = static_cast<i32>(GD_INT_GET(PATH_DAMAGE_WEIGHT));
    // Promotion identifier.
    out.promotionUnwelcomeEvangelist = static_cast<i32>(GD_INT_GET(PROMOTION_UNWELCOME_EVANGELIST));
    // GD_INT_GET define.
    out.riverAttackModifier = static_cast<i32>(GD_INT_GET(RIVER_ATTACK_MODIFIER));
    // GD_INT_GET define.
    out.attackingCityMeleeDamageMod = static_cast<i32>(GD_INT_GET(ATTACKING_CITY_MELEE_DAMAGE_MOD));
    // GD_INT_GET define.
    out.attackSameStrengthMinDamage = static_cast<i32>(GD_INT_GET(ATTACK_SAME_STRENGTH_MIN_DAMAGE));
    // GD_INT_GET define.
    out.attackSameStrengthPossibleExtraDamage = static_cast<i32>(GD_INT_GET(ATTACK_SAME_STRENGTH_POSSIBLE_EXTRA_DAMAGE));
    // GD_INT_GET define.
    out.cityAttackingDamageMod = static_cast<i32>(GD_INT_GET(CITY_ATTACKING_DAMAGE_MOD));
    // GD_INT_GET define.
    out.woundedDamageMultiplier = static_cast<i32>(GD_INT_GET(WOUNDED_DAMAGE_MULTIPLIER));
    // GD_INT_GET define.
    out.barbarianCityAttackModifier = static_cast<i32>(GD_INT_GET(BARBARIAN_CITY_ATTACK_MODIFIER));
    // GD_INT_GET define.
    out.policyAttackBonusMod = static_cast<i32>(GD_INT_GET(POLICY_ATTACK_BONUS_MOD));
    // GD_INT_GET define.
    out.navalCombatDefenderStrengthMultiplier = static_cast<i32>(GD_INT_GET(NAVAL_COMBAT_DEFENDER_STRENGTH_MULTIPLIER));
    // GD_INT_GET define.
    out.balanceMaxCsAllyStrength = static_cast<i32>(GD_INT_GET(BALANCE_MAX_CS_ALLY_STRENGTH));
    // GD_INT_GET define.
    out.mountainSeeFromChange = static_cast<i32>(GD_INT_GET(MOUNTAIN_SEE_FROM_CHANGE));
    // GD_INT_GET define.
    out.hillsSeeFromChange = static_cast<i32>(GD_INT_GET(HILLS_SEE_FROM_CHANGE));
    // GD_INT_GET define.
    out.seawaterSeeFromChange = static_cast<i32>(GD_INT_GET(SEAWATER_SEE_FROM_CHANGE));
    // GD_INT_GET define.
    out.mountainSeeThroughChange = static_cast<i32>(GD_INT_GET(MOUNTAIN_SEE_THROUGH_CHANGE));
    // GD_INT_GET define.
    out.hillsSeeThroughChange = static_cast<i32>(GD_INT_GET(HILLS_SEE_THROUGH_CHANGE));
    // GD_INT_GET define.
    out.seawaterSeeThroughChange = static_cast<i32>(GD_INT_GET(SEAWATER_SEE_THROUGH_CHANGE));
    // GD_INT_GET boolean define.
    out.ignoreGlobalTerrainCostsIncludesRivers = (GD_INT_GET(IGNORE_GLOBAL_TERRAIN_COSTS_INCLUDES_RIVERS)) ? 1 : 0;
    // GD_INT_GET boolean define.
    out.ignoreSpecificTerrainCostsIncludesRivers = (GD_INT_GET(IGNORE_SPECIFIC_TERRAIN_COSTS_INCLUDES_RIVERS)) ? 1 : 0;
    // GD_INT_GET boolean define.
    out.zoneOfControlEnabled = (GD_INT_GET(ZONE_OF_CONTROL_ENABLED)) ? 1 : 0;
    // Native source checks the file-local #define FOG_DEFAULT_DANGER (1); the generated collector uses the equivalent reachable literal.
    out.fogDefaultDanger = static_cast<u8>(1);
    // Compile-time mod flag.
    out.modCoreDelayedVisibility = (MOD_CORE_DELAYED_VISIBILITY) ? 1 : 0;
    // Compile-time mod flag.
    out.modBalanceRangedDefenseUnitHealth = (MOD_BALANCE_RANGED_DEFENSE_UNIT_HEALTH) ? 1 : 0;
    // Compile-time mod flag.
    out.modCombatAiTwoPassDanger = (MOD_COMBATAI_TWO_PASS_DANGER) ? 1 : 0;
    // Compile-time mod flag.
    out.modBalanceVp = (MOD_BALANCE_VP) ? 1 : 0;
    // Compile-time mod flag.
    out.modApiHoveringUnits = (MOD_API_HOVERING_UNITS) ? 1 : 0;
    return true;
}

bool CollectStaticHandicapLimitsRecord(StaticHandicapLimitsRecord& out)
{
    // Active handicap value.
    out.maxBranches = static_cast<i32>(GC.getGame().getHandicapInfo().getTacticalSimMaxBranches());
    // Active handicap value.
    out.maxChoicesPerUnit = static_cast<i32>(GC.getGame().getHandicapInfo().getTacticalSimMaxChoicesPerUnit());
    // Active handicap value.
    out.maxCompletedPositions = static_cast<i32>(GC.getGame().getHandicapInfo().getTacticalSimMaxCompletedPositions());
    return true;
}

bool CollectTerrainInfoRecord(CvTerrainInfo& terrainInfo, TerrainInfoRecord& out)
{
    // Terrain movement cost.
    out.movementCost = static_cast<i32>(terrainInfo.getMovementCost());
    // Terrain vantage level.
    out.seeFromLevel = static_cast<i32>(terrainInfo.getSeeFromLevel());
    // Terrain sight-through level.
    out.seeThroughLevel = static_cast<i32>(terrainInfo.getSeeThroughLevel());
    // Terrain turn damage.
    out.turnDamage = static_cast<i32>(terrainInfo.getTurnDamage());
    // Terrain impassability.
    out.impassable = (terrainInfo.isImpassable()) ? 1 : 0;
    return true;
}

bool CollectFeatureInfoRecord(CvFeatureInfo& featureInfo, FeatureInfoRecord& out)
{
    // Feature movement cost.
    out.movementCost = static_cast<i32>(featureInfo.getMovementCost());
    // Feature sight-through change.
    out.seeThroughChange = static_cast<i32>(featureInfo.getSeeThroughChange());
    // Feature turn damage.
    out.turnDamage = static_cast<i32>(featureInfo.getTurnDamage());
    return true;
}

bool CollectRouteInfoRecord(CvRouteInfo& routeInfo, RouteInfoRecord& out)
{
    // Route movement cost.
    out.movementCost = static_cast<i32>(routeInfo.getMovementCost());
    // Route flat movement cost.
    out.flatMovementCost = static_cast<i32>(routeInfo.getFlatMovementCost());
    return true;
}

bool CollectImprovementInfoRecord(CvImprovementEntry& improvementInfo, ImprovementInfoRecord& out)
{
    // Improvement defense modifier.
    out.defenseModifier = static_cast<i32>(improvementInfo.GetDefenseModifier());
    // Nearby enemy damage.
    out.nearbyEnemyDamage = static_cast<i32>(improvementInfo.GetNearbyEnemyDamage());
    // No-follow-up flag.
    out.noFollowUp = (improvementInfo.IsNoFollowUp()) ? 1 : 0;
    return true;
}

bool CollectResourceInfoRecord(CvResourceInfo& resourceInfo, ResourceInfoRecord& out)
{
    // Resource usage class.
    out.resourceUsage = static_cast<u8>(resourceInfo.getResourceUsage());
    return true;
}

bool CollectUnitEntryInfoRecord(CvUnitEntry& unitEntry, UnitEntryInfoRecord& out)
{
    // Default unit AI type.
    out.defaultUnitAiType = static_cast<i8>(unitEntry.GetDefaultUnitAIType());
    return true;
}

bool CollectStaticBuildIdsRecord(StaticBuildIdsRecord& out)
{
    // BUILD_CITADEL identifier.
    out.citadel = static_cast<i32>(GC.getInfoTypeForString("BUILD_CITADEL"));
    // BUILD_ORDO identifier when balance VP is active.
    out.ordo = static_cast<i32>(GC.getInfoTypeForString("BUILD_ORDO"));
    // BUILD_ISIBAYA identifier when balance VP is active.
    out.isibaya = static_cast<i32>(GC.getInfoTypeForString("BUILD_ISIBAYA"));
    return true;
}

bool CollectMapTopologyRecord(CvMap& map, MapTopologyRecord& out)
{
    // Map width.
    out.gridWidth = static_cast<i32>(map.getGridWidth());
    // Map height.
    out.gridHeight = static_cast<i32>(map.getGridHeight());
    // Horizontal wrapping.
    out.wrapX = (map.isWrapX()) ? 1 : 0;
    // Vertical wrapping.
    out.wrapY = (map.isWrapY()) ? 1 : 0;
    return true;
}

bool CollectPlotTopologyRecord(CvPlot& plot, PlotTopologyRecord& out)
{
    // River crossing count.
    out.riverCrossingCount = static_cast<i32>(plot.getRiverCrossingCount());
    // Area identifier.
    out.area = static_cast<i32>(plot.getArea());
    // Landmass identifier.
    out.landmass = static_cast<i32>(plot.getLandmass());
    // Terrain type.
    out.terrainType = static_cast<i8>(plot.getTerrainType());
    // Flat, hill, mountain, or water plot type.
    out.plotType = static_cast<i8>(plot.getPlotType());
    // Hill flag.
    out.hills = (plot.isHills()) ? 1 : 0;
    // Mountain flag.
    out.mountain = (plot.isMountain()) ? 1 : 0;
    // Water flag.
    out.water = (plot.isWater()) ? 1 : 0;
    // Deep-water flag.
    out.deepWater = (plot.isDeepWater()) ? 1 : 0;
    // Lake flag.
    out.lake = (plot.isLake()) ? 1 : 0;
    // Coastal-land flag.
    out.coastalLand = (plot.isCoastalLand()) ? 1 : 0;
    // River flag.
    out.river = (plot.isRiver()) ? 1 : 0;
    // Per-direction river-crossing flags.
    for (int index = 0; index < 1; ++index) {
        out.riverCrossing[index] = 0;
    }
    if ((NUM_DIRECTION_TYPES) > VoxRlDirectionCapacity) {
        return false;
    }
    for (int index = 0; index < (NUM_DIRECTION_TYPES); ++index) {
        if (plot.isRiverCrossing(static_cast<DirectionTypes>(index))) {
            out.riverCrossing[index / 8] = static_cast<u8>(out.riverCrossing[index / 8] | (1 << (index % 8)));
        }
    }
    // Northeast river flow.
    out.northEastRiver = (plot.isNEOfRiver()) ? 1 : 0;
    // West river flow.
    out.westRiver = (plot.isWOfRiver()) ? 1 : 0;
    // Northwest river flow.
    out.northWestRiver = (plot.isNWOfRiver()) ? 1 : 0;
    // Native return type is char.
    out.continentType = static_cast<i8>(plot.GetContinentType());
    // Base terrain impassability.
    out.impassable = (plot.isImpassable()) ? 1 : 0;
    // Lowercase native accessor.
    out.roughGround = (plot.isRoughGround()) ? 1 : 0;
    return true;
}

bool CollectPlotDynamicRecord(CvPlot& plot, VoxRlCaptureIndex& lookup, PlotDynamicRecord& out)
{
    // Improvement type.
    out.improvementType = static_cast<i32>(plot.getImprovementType());
    // Resource type using native defaults.
    out.resourceType = static_cast<i32>(plot.getResourceType());
    // Portable city-record index.
    out.cityIndex = static_cast<i32>(plot.isCity() ? lookup.cityIndex(plot.getPlotCity()->GetID()) : -1);
    // Recon count.
    out.reconCount = static_cast<i32>(plot.getReconCount());
    // Extra path movement cost.
    out.extraMovePathCost = static_cast<i32>(plot.getExtraMovePathCost());
    // Filled from the refreshed tactical analysis map.
    // zoneId has no generated assignment because its capture mode is builder.
    // Units are sorted globally by plot index then unit ID.
    // unitRange has no generated assignment because its capture mode is builder.
    // Owning player.
    out.owner = static_cast<i8>(plot.getOwner());
    // Dynamic feature type.
    out.featureType = static_cast<i8>(plot.getFeatureType());
    // Improvement pillage state.
    out.improvementPillaged = (plot.IsImprovementPillaged()) ? 1 : 0;
    // Improvement movement passability.
    out.improvementPassable = (plot.IsImprovementPassable()) ? 1 : 0;
    // Route type.
    out.routeType = static_cast<i8>(plot.getRouteType());
    // Capitalized native accessor.
    out.routePillaged = (plot.IsRoutePillaged()) ? 1 : 0;
    // City presence.
    out.hasCity = (plot.isCity()) ? 1 : 0;
    // Restore-moves flag.
    out.restoreMoves = (plot.IsRestoreMoves()) ? 1 : 0;
    // Free movement edge flag.
    out.freeMoveAcross = (plot.IsFreeMoveAcross()) ? 1 : 0;
    return true;
}

bool CollectPlotTeamRecord(TeamTypes otherTeam, PlotTeamRecord& out)
{
    // Sparse values whose revealed state differs from actual state.
    // revealedOverrideRange has no generated assignment because its capture mode is builder.
    // Native team identifier.
    out.team = static_cast<i8>(otherTeam);
    return true;
}

bool CollectRevealedOverrideRecord(CvPlot& plot, TeamTypes otherTeam, RevealedOverrideRecord& out)
{
    // Plot index.
    out.plotIndex = static_cast<i32>(plot.GetPlotIndex());
    // Ordinary non-debug overload.
    out.revealedImprovementType = static_cast<i32>(plot.getRevealedImprovementType(otherTeam));
    // Ordinary non-debug overload.
    out.revealedOwner = static_cast<i32>(plot.getRevealedOwner(otherTeam));
    // Viewing team.
    out.team = static_cast<i8>(otherTeam);
    // Ordinary non-debug overload.
    out.revealedRouteType = static_cast<i8>(plot.getRevealedRouteType(otherTeam));
    return true;
}

bool CollectUnitRecord(CvUnit& unit, TeamTypes capturingTeam, UnitRecord& out)
{
    // Capitalized native accessor.
    out.id = static_cast<i32>(unit.GetID());
    // Unit type.
    out.unitType = static_cast<i32>(unit.getUnitType());
    // Current portable plot index.
    out.plotIndex = static_cast<i32>(unit.plot()->GetPlotIndex());
    // Current x coordinate.
    out.x = static_cast<i32>(unit.getX());
    // Current y coordinate.
    out.y = static_cast<i32>(unit.getY());
    // Current damage.
    out.damage = static_cast<i32>(unit.getDamage());
    // Current hit points.
    out.currentHitPoints = static_cast<i32>(unit.GetCurrHitPoints());
    // Maximum hit points.
    out.maxHitPoints = static_cast<i32>(unit.GetMaxHitPoints());
    // Remaining fixed-point moves.
    out.moves = static_cast<i32>(unit.getMoves());
    // This accessor takes no argument.
    out.maxMoves = static_cast<i32>(unit.maxMoves());
    // bPretendEmbarked is false.
    out.baseMoves = static_cast<i32>(unit.baseMoves(false));
    // Attack count used to derive attacks left.
    out.numAttacks = static_cast<i32>(unit.getNumAttacks());
    // Unit level.
    out.level = static_cast<i32>(unit.getLevel());
    // Experience scaled by 100.
    out.experienceTimes100 = static_cast<i32>(unit.getExperienceTimes100());
    // Current army identifier.
    out.armyId = static_cast<i32>(unit.getArmyID());
    // Ranged attack range.
    out.range = static_cast<i32>(unit.GetRange());
    // Power score.
    out.power = static_cast<i32>(unit.GetPower());
    // Base melee strength.
    out.baseCombatStrength = static_cast<i32>(unit.GetBaseCombatStrength());
    // Unit visibility range.
    out.visibilityRange = static_cast<i32>(unit.visibilityRange());
    // Multi-attack bonus.
    out.multiAttackBonus = static_cast<i32>(unit.getMultiAttackBonus());
    // Splash damage.
    out.splashDamage = static_cast<i32>(unit.getSplashDamage());
    // City attack plunder modifier.
    out.cityAttackPlunderModifier = static_cast<i32>(unit.GetCityAttackPlunderModifier());
    // Damage taken last turn.
    out.damageTakenLastTurn = static_cast<i32>(unit.GetDamageTakenLastTurn());
    // Flanking input.
    out.flankAttackModifier = static_cast<i32>(unit.GetFlankAttackModifier());
    // Ranged modifier input.
    out.rangedAttackModifier = static_cast<i32>(unit.GetRangedAttackModifier());
    // Interception modifier input.
    out.interceptionCombatModifier = static_cast<i32>(unit.GetInterceptionCombatModifier());
    // Extra movement discount.
    out.extraMoveDiscount = static_cast<i32>(unit.getExtraMoveDiscount());
    // Per-terrain extra-move counts.
    for (int index = 0; index < 32; ++index) {
        out.terrainExtraMoveCount[index] = 0;
    }
    if ((GC.getNumTerrainInfos()) > VoxRlTerrainCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumTerrainInfos()); ++index) {
        out.terrainExtraMoveCount[index] = static_cast<i32>(unit.getTerrainExtraMoveCount(static_cast<TerrainTypes>(index)));
    }
    // Per-feature extra-move counts.
    for (int index = 0; index < 64; ++index) {
        out.featureExtraMoveCount[index] = 0;
    }
    if ((GC.getNumFeatureInfos()) > VoxRlFeatureCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumFeatureInfos()); ++index) {
        out.featureExtraMoveCount[index] = static_cast<i32>(unit.getFeatureExtraMoveCount(static_cast<FeatureTypes>(index)));
    }
    // Same-tile healing.
    out.sameTileHeal = static_cast<i32>(unit.getSameTileHeal());
    // Adjacent-tile healing.
    out.adjacentTileHeal = static_cast<i32>(unit.getAdjacentTileHeal());
    // Friendly-territory healing.
    out.extraFriendlyHeal = static_cast<i32>(unit.getExtraFriendlyHeal());
    // Enemy-territory healing.
    out.extraEnemyHeal = static_cast<i32>(unit.getExtraEnemyHeal());
    // Neutral-territory healing.
    out.extraNeutralHeal = static_cast<i32>(unit.getExtraNeutralHeal());
    // Flat heal rate.
    out.flatHealRate = static_cast<i32>(unit.GetFlatHealRate());
    // Aura range change.
    out.auraRangeChange = static_cast<i32>(unit.GetAuraRangeChange());
    // Aura effect change.
    out.auraEffectChange = static_cast<i32>(unit.GetAuraEffectChange());
    // Adjacent city defense modifier.
    out.adjacentCityDefenseMod = static_cast<i32>(unit.GetAdjacentCityDefenseMod());
    // Fortified area damage.
    out.damageAoeFortified = static_cast<i32>(unit.GetDamageAoEFortified());
    // Area damage on move.
    out.aoeDamageOnMove = static_cast<i32>(unit.getAoEDamageOnMove());
    // Tile damage when stationary.
    out.tileDamageIfNotMoved = static_cast<i32>(unit.GetTileDamageIfNotMoved());
    // Extra experience on kill.
    out.extraXpOnKill = static_cast<i32>(unit.GetExtraXPOnKill());
    // Healing after defeating an enemy.
    out.hpHealedIfDefeatEnemy = static_cast<i32>(unit.getHPHealedIfDefeatEnemy());
    // Golden-age value from kills.
    out.goldenAgeValueFromKills = static_cast<i32>(unit.GetGoldenAgeValueFromKills());
    // Area healing on pillage.
    out.aoeHealOnPillage = static_cast<i32>(unit.getAOEHealOnPillage());
    // Area damage on pillage.
    out.aoeDamageOnPillage = static_cast<i32>(unit.getAOEDamageOnPillage());
    // Experience from pillaging.
    out.xpFromPillaging = static_cast<i32>(unit.GetXPFromPillaging());
    // Attack modifier when wounded.
    out.attackWoundedModifier = static_cast<i32>(unit.attackWoundedModifier());
    // Attack modifier when fully healed.
    out.attackFullyHealedModifier = static_cast<i32>(unit.attackFullyHealedModifier());
    // Attack modifier above half health.
    out.attackAbove50HealthModifier = static_cast<i32>(unit.attackAbove50HealthModifier());
    // Attack modifier below half health.
    out.attackBelow50HealthModifier = static_cast<i32>(unit.attackBelow50HealthModifier());
    // Owner player.
    out.owner = static_cast<i8>(unit.getOwner());
    // Owner team.
    out.team = static_cast<i8>(unit.getTeam());
    // Current unit AI type.
    out.unitAiType = static_cast<i8>(unit.AI_getUnitAIType());
    // Unit-entry default AI type.
    out.defaultUnitAiType = static_cast<i8>(unit.getUnitInfo().GetDefaultUnitAIType());
    // The required checkLineOfSightProperty argument is false.
    out.facing = static_cast<i8>(unit.getFacingDirection(false));
    // Moved this turn.
    out.hasMoved = (unit.hasMoved()) ? 1 : 0;
    // No attacks remaining.
    out.outOfAttacks = (unit.isOutOfAttacks()) ? 1 : 0;
    // Embarked state.
    out.embarked = (unit.isEmbarked()) ? 1 : 0;
    // Cargo state.
    out.cargo = (unit.isCargo()) ? 1 : 0;
    // Excluded units are filtered by the builder.
    out.delayedDeath = (unit.isDelayedDeath()) ? 1 : 0;
    // Dead state.
    out.dead = (unit.IsDead()) ? 1 : 0;
    // Turn processing flag.
    out.turnProcessed = (unit.TurnProcessed()) ? 1 : 0;
    // Immobile state.
    out.immobile = (unit.IsImmobile()) ? 1 : 0;
    // Automation state.
    out.automated = (unit.IsAutomated()) ? 1 : 0;
    // Read through the owning player.
    out.ownerHuman = (GET_PLAYER(unit.getOwner()).isHuman()) ? 1 : 0;
    // Domain type.
    out.domainType = static_cast<i8>(unit.getDomainType());
    // Combat-unit flag.
    out.combatUnit = (unit.IsCombatUnit()) ? 1 : 0;
    // Civilian-unit flag.
    out.civilianUnit = (unit.IsCivilianUnit()) ? 1 : 0;
    // Can defend.
    out.canDefend = (unit.IsCanDefend()) ? 1 : 0;
    // Can attack.
    out.canAttack = (unit.IsCanAttack()) ? 1 : 0;
    // Can attack at range.
    out.canAttackRanged = (unit.IsCanAttackRanged()) ? 1 : 0;
    // Can attack while moving.
    out.canAttackWithMove = (unit.IsCanAttackWithMove()) ? 1 : 0;
    // Can move after attacking.
    out.moveAfterAttacking = (unit.canMoveAfterAttacking()) ? 1 : 0;
    // Free attack movement flag.
    out.freeAttackMoves = (unit.IsFreeAttackMoves()) ? 1 : 0;
    // Ranged support fire flag.
    out.rangedSupportFire = (unit.isRangedSupportFire()) ? 1 : 0;
    // Range attacks ignore line of sight.
    out.rangeAttackIgnoreLos = (unit.IsRangeAttackIgnoreLOS()) ? 1 : 0;
    // Can make a range strike.
    out.canRangeStrike = (unit.canRangeStrike()) ? 1 : 0;
    // Verified native accessor.
    out.setUpForRangedAttack = (unit.isSetUpForRangedAttack()) ? 1 : 0;
    // No-capture flag.
    out.noCapture = (unit.isNoCapture()) ? 1 : 0;
    // Verified native accessor.
    out.suicide = (unit.isSuicide()) ? 1 : 0;
    // Barbarian flag.
    out.barbarian = (unit.isBarbarian()) ? 1 : 0;
    // Can intercept.
    out.canIntercept = (unit.canIntercept()) ? 1 : 0;
    // Uses the non-debug observer-team overload.
    out.invisible = (unit.isInvisible(capturingTeam, false)) ? 1 : 0;
    // Great-general flag.
    out.greatGeneral = (unit.IsGreatGeneral()) ? 1 : 0;
    // Great-admiral flag.
    out.greatAdmiral = (unit.IsGreatAdmiral()) ? 1 : 0;
    // Sapper flag.
    out.sapper = (unit.IsSapper()) ? 1 : 0;
    // City attack support flag.
    out.cityAttackSupport = (unit.IsCityAttackSupport()) ? 1 : 0;
    // Can ever fortify.
    out.everFortifyable = (unit.IsEverFortifyable()) ? 1 : 0;
    // Combat state.
    out.inCombat = (unit.isInCombat()) ? 1 : 0;
    // Leadership requirement.
    out.requiresLeadership = (unit.IsRequiresLeadership()) ? 1 : 0;
    // Ignore zone of control.
    out.ignoreZoc = (unit.IsIgnoreZOC()) ? 1 : 0;
    // Hovering unit flag.
    out.hovering = (unit.IsHoveringUnit()) ? 1 : 0;
    // Can ever embark.
    out.canEverEmbark = (unit.CanEverEmbark()) ? 1 : 0;
    // Flat movement cost flag.
    out.flatMovementCost = (unit.flatMovementCost()) ? 1 : 0;
    // Disembark flat cost flag.
    out.disembarkFlatCost = (unit.isDisembarkFlatCost()) ? 1 : 0;
    // Embark flat cost flag.
    out.embarkFlatCost = (unit.isEmbarkFlatCost()) ? 1 : 0;
    // Convert-unit flag.
    out.convertUnit = (unit.isConvertUnit()) ? 1 : 0;
    // Rough terrain ends turn.
    out.roughTerrainEndsTurn = (unit.IsRoughTerrainEndsTurn()) ? 1 : 0;
    // Ignore terrain cost.
    out.ignoreTerrainCost = (unit.ignoreTerrainCost()) ? 1 : 0;
    // River crossing has no penalty.
    out.riverCrossingNoPenalty = (unit.isRiverCrossingNoPenalty()) ? 1 : 0;
    // River double move.
    out.riverDoubleMove = (unit.isRiverDoubleMove()) ? 1 : 0;
    // Slow in enemy land.
    out.slowInEnemyLand = (unit.isSlowInEnemyLand()) ? 1 : 0;
    // Amphibious flag.
    out.amphibious = (unit.isAmphibious()) ? 1 : 0;
    // No-reveal-map flag.
    out.noRevealMap = (unit.isNoRevealMap()) ? 1 : 0;
    // Ignore terrain damage.
    out.ignoreTerrainDamage = (unit.ignoreTerrainDamage()) ? 1 : 0;
    // Ignore feature damage.
    out.ignoreFeatureDamage = (unit.ignoreFeatureDamage()) ? 1 : 0;
    // Extra terrain damage.
    out.extraTerrainDamage = (unit.extraTerrainDamage()) ? 1 : 0;
    // Extra feature damage.
    out.extraFeatureDamage = (unit.extraFeatureDamage()) ? 1 : 0;
    // Promotion identifier comes from static rules.
    out.unwelcomeEvangelist = (unit.isHasPromotion(static_cast<PromotionTypes>(GD_INT_GET(PROMOTION_UNWELCOME_EVANGELIST)))) ? 1 : 0;
    // Anger-free unit.
    out.angerFree = (unit.IsAngerFreeUnit()) ? 1 : 0;
    // Per-terrain flags.
    for (int index = 0; index < 4; ++index) {
        out.ignoreTerrainCostIn[index] = 0;
    }
    if ((GC.getNumTerrainInfos()) > VoxRlTerrainCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumTerrainInfos()); ++index) {
        if (unit.isIgnoreTerrainCostIn(static_cast<TerrainTypes>(index))) {
            out.ignoreTerrainCostIn[index / 8] = static_cast<u8>(out.ignoreTerrainCostIn[index / 8] | (1 << (index % 8)));
        }
    }
    // Per-terrain flags.
    for (int index = 0; index < 4; ++index) {
        out.ignoreTerrainCostFrom[index] = 0;
    }
    if ((GC.getNumTerrainInfos()) > VoxRlTerrainCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumTerrainInfos()); ++index) {
        if (unit.isIgnoreTerrainCostFrom(static_cast<TerrainTypes>(index))) {
            out.ignoreTerrainCostFrom[index / 8] = static_cast<u8>(out.ignoreTerrainCostFrom[index / 8] | (1 << (index % 8)));
        }
    }
    // Per-terrain flags.
    for (int index = 0; index < 4; ++index) {
        out.terrainDoubleMove[index] = 0;
    }
    if ((GC.getNumTerrainInfos()) > VoxRlTerrainCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumTerrainInfos()); ++index) {
        if (unit.isTerrainDoubleMove(static_cast<TerrainTypes>(index))) {
            out.terrainDoubleMove[index / 8] = static_cast<u8>(out.terrainDoubleMove[index / 8] | (1 << (index % 8)));
        }
    }
    // Per-terrain flags.
    for (int index = 0; index < 4; ++index) {
        out.terrainHalfMove[index] = 0;
    }
    if ((GC.getNumTerrainInfos()) > VoxRlTerrainCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumTerrainInfos()); ++index) {
        if (unit.isTerrainHalfMove(static_cast<TerrainTypes>(index))) {
            out.terrainHalfMove[index / 8] = static_cast<u8>(out.terrainHalfMove[index / 8] | (1 << (index % 8)));
        }
    }
    // Per-terrain flags.
    for (int index = 0; index < 4; ++index) {
        out.terrainExtraMove[index] = 0;
    }
    if ((GC.getNumTerrainInfos()) > VoxRlTerrainCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumTerrainInfos()); ++index) {
        if (unit.isTerrainExtraMove(static_cast<TerrainTypes>(index))) {
            out.terrainExtraMove[index / 8] = static_cast<u8>(out.terrainExtraMove[index / 8] | (1 << (index % 8)));
        }
    }
    // Per-feature flags.
    for (int index = 0; index < 8; ++index) {
        out.ignoreFeatureCostIn[index] = 0;
    }
    if ((GC.getNumFeatureInfos()) > VoxRlFeatureCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumFeatureInfos()); ++index) {
        if (unit.isIgnoreFeatureCostIn(static_cast<FeatureTypes>(index))) {
            out.ignoreFeatureCostIn[index / 8] = static_cast<u8>(out.ignoreFeatureCostIn[index / 8] | (1 << (index % 8)));
        }
    }
    // Per-feature flags.
    for (int index = 0; index < 8; ++index) {
        out.ignoreFeatureCostFrom[index] = 0;
    }
    if ((GC.getNumFeatureInfos()) > VoxRlFeatureCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumFeatureInfos()); ++index) {
        if (unit.isIgnoreFeatureCostFrom(static_cast<FeatureTypes>(index))) {
            out.ignoreFeatureCostFrom[index / 8] = static_cast<u8>(out.ignoreFeatureCostFrom[index / 8] | (1 << (index % 8)));
        }
    }
    // Per-feature flags.
    for (int index = 0; index < 8; ++index) {
        out.featureDoubleMove[index] = 0;
    }
    if ((GC.getNumFeatureInfos()) > VoxRlFeatureCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumFeatureInfos()); ++index) {
        if (unit.isFeatureDoubleMove(static_cast<FeatureTypes>(index))) {
            out.featureDoubleMove[index / 8] = static_cast<u8>(out.featureDoubleMove[index / 8] | (1 << (index % 8)));
        }
    }
    // Per-feature flags.
    for (int index = 0; index < 8; ++index) {
        out.featureHalfMove[index] = 0;
    }
    if ((GC.getNumFeatureInfos()) > VoxRlFeatureCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumFeatureInfos()); ++index) {
        if (unit.isFeatureHalfMove(static_cast<FeatureTypes>(index))) {
            out.featureHalfMove[index / 8] = static_cast<u8>(out.featureHalfMove[index / 8] | (1 << (index % 8)));
        }
    }
    // Per-feature flags.
    for (int index = 0; index < 8; ++index) {
        out.featureExtraMove[index] = 0;
    }
    if ((GC.getNumFeatureInfos()) > VoxRlFeatureCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumFeatureInfos()); ++index) {
        if (unit.isFeatureExtraMove(static_cast<FeatureTypes>(index))) {
            out.featureExtraMove[index / 8] = static_cast<u8>(out.featureExtraMove[index / 8] | (1 << (index % 8)));
        }
    }
    // Always-heal flag.
    out.alwaysHeal = (unit.isAlwaysHeal()) ? 1 : 0;
    // Pillage fortifications on kill.
    out.pillageFortificationsOnKill = (unit.IsPillageFortificationsOnKill()) ? 1 : 0;
    // Free pillage move.
    out.freePillageMove = (unit.hasFreePillageMove()) ? 1 : 0;
    // Stronger-damaged promotion flag.
    out.strongerDamaged = (unit.IsStrongerDamaged()) ? 1 : 0;
    // Fight-well-damaged promotion flag.
    out.fightWellDamaged = (unit.IsFightWellDamaged()) ? 1 : 0;
    return true;
}

bool CollectCityRecord(CvCity& city, PlayerTypes capturingPlayer, CityRecord& out)
{
    bool indirectFireAllowed = false;

    // Stable city identifier.
    out.id = static_cast<i32>(city.GetID());
    // Portable city plot index.
    out.plotIndex = static_cast<i32>(city.plot()->GetPlotIndex());
    // Maximum hit points.
    out.maxHitPoints = static_cast<i32>(city.GetMaxHitPoints());
    // Current damage.
    out.damage = static_cast<i32>(city.getDamage());
    // Normal, non-range-strike strength.
    out.strengthValue = static_cast<i32>(city.getStrengthValue(false));
    // The mutable indirect-fire output is captured below.
    out.bombardRange = static_cast<i32>(city.getBombardRange(indirectFireAllowed));
    // Stable garrison unit identifier or -1.
    out.garrisonUnitId = static_cast<i32>(city.GetGarrisonedUnit() ? city.GetGarrisonedUnit()->GetID() : -1);
    // Damage taken last turn.
    out.damageTakenLastTurn = static_cast<i32>(city.getDamageTakenLastTurn());
    // Requires the operational player and is non-const.
    out.economicValue = static_cast<i32>(city.getEconomicValue(capturingPlayer));
    // Owner player.
    out.owner = static_cast<i8>(city.getOwner());
    // Owner team.
    out.team = static_cast<i8>(city.getTeam());
    // Can make a ranged strike.
    out.canRangeStrike = (city.canRangeStrike()) ? 1 : 0;
    // Set by getBombardRange(bool&).
    out.indirectFireAllowed = (indirectFireAllowed) ? 1 : 0;
    // Land and water blockade state.
    out.blockadedWaterAndLand = (city.IsBlockadedWaterAndLand()) ? 1 : 0;
    // Native default carefulness.
    out.inDangerOfFalling = (city.isInDangerOfFalling()) ? 1 : 0;
    // Native default minimum water size.
    out.coastal = (city.isCoastal()) ? 1 : 0;
    // Original capital flag.
    out.originalCapital = (city.IsOriginalCapital()) ? 1 : 0;
    // Original owner.
    out.originalOwner = static_cast<i8>(city.getOriginalOwner());
    return true;
}

bool CollectTeamRelationRecord(CvTeam& team, TeamTypes otherTeam, PlayerTypes capturingPlayer, TeamRelationRecord& out)
{
    // Source team.
    out.team = static_cast<i8>(team.GetID());
    // Target team.
    out.otherTeam = static_cast<i8>(otherTeam);
    // War relation.
    out.atWar = (team.isAtWar(otherTeam)) ? 1 : 0;
    // Open-borders relation.
    out.allowsOpenBorders = (team.IsAllowsOpenBordersToTeam(otherTeam)) ? 1 : 0;
    // Met relation.
    out.hasMet = (team.isHasMet(otherTeam)) ? 1 : 0;
    // Forced-peace relation.
    out.forcePeace = (team.isForcePeace(otherTeam)) ? 1 : 0;
    // War declaration for the capturing player.
    out.canDeclareWar = (team.canDeclareWar(otherTeam, capturingPlayer)) ? 1 : 0;
    return true;
}

bool CollectTeamRecord(CvTeam& team, TeamRecord& out)
{
    // Per-route movement change.
    for (int index = 0; index < 8; ++index) {
        out.routeChange[index] = 0;
    }
    if ((GC.getNumRouteInfos()) > VoxRlRouteCapacity) {
        return false;
    }
    for (int index = 0; index < (GC.getNumRouteInfos()); ++index) {
        out.routeChange[index] = static_cast<i32>(team.getRouteChange(static_cast<RouteTypes>(index)));
    }
    // Stable team identifier.
    out.id = static_cast<i8>(team.GetID());
    // Minor civilization team.
    out.minorCiv = (team.isMinorCiv()) ? 1 : 0;
    // Barbarian team.
    out.barbarian = (team.isBarbarian()) ? 1 : 0;
    // Bridge-building ability.
    out.bridgeBuilding = (team.isBridgeBuilding()) ? 1 : 0;
    // Border obstacle flag.
    out.borderObstacle = (team.isBorderObstacle()) ? 1 : 0;
    // No embark cost in cities.
    out.cityNoEmbarkCost = (team.isCityNoEmbarkCost()) ? 1 : 0;
    // Reduced embark cost in cities.
    out.cityLessEmbarkCost = (team.isCityLessEmbarkCost()) ? 1 : 0;
    // Extra water vantage level.
    out.extraWaterSeeFrom = (team.isExtraWaterSeeFrom()) ? 1 : 0;
    // Ocean-crossing construction ability.
    out.canBuildOceanCrossingUnit = (team.CanBuildOceanCrossingUnit()) ? 1 : 0;
    return true;
}

bool CollectPlayerRecord(CvPlayer& player, PlayerTypes otherPlayer, PlayerRecord& out)
{
    // Trait owned by CvPlayerTraits.
    out.multipleAttackBonus = static_cast<i32>(player.GetPlayerTraits()->GetMultipleAttackBonus());
    // Trait owned by CvPlayerTraits.
    out.greatGeneralExtraBonus = static_cast<i32>(player.GetPlayerTraits()->GetGreatGeneralExtraBonus());
    // Wounded unit damage modifier.
    out.woundedUnitDamageMod = static_cast<i32>(player.GetWoundedUnitDamageMod());
    // Great general combat bonus.
    out.greatGeneralCombatBonus = static_cast<i32>(player.GetGreatGeneralCombatBonus());
    // Average unit experience scaled by 100.
    out.avgUnitExp100 = static_cast<i32>(player.GetAvgUnitExp100());
    // Personality and grand-strategy offense flavor.
    out.offenseFlavor = static_cast<i32>(player.GetGrandStrategyAI()->GetPersonalityAndGrandStrategy(static_cast<FlavorTypes>(GC.getInfoTypeForString("FLAVOR_OFFENSE"))));
    // Non-const accessor, captured per domain.
    for (int index = 0; index < 8; ++index) {
        out.offensiveOperations[index] = 0;
    }
    if ((NUM_DOMAIN_TYPES) > VoxRlDomainCapacity) {
        return false;
    }
    for (int index = 0; index < (NUM_DOMAIN_TYPES); ++index) {
        out.offensiveOperations[index] = static_cast<i32>(player.GetNumOffensiveOperations(static_cast<DomainTypes>(index)));
    }
    // Current supplied units.
    out.unitsSupplied = static_cast<i32>(player.GetNumUnitsSupplied());
    // Current unsupplied units.
    out.unitsOutOfSupply = static_cast<i32>(player.GetNumUnitsOutOfSupply());
    // Stable player identifier.
    out.id = static_cast<i8>(otherPlayer);
    // Human player flag.
    out.human = (player.isHuman()) ? 1 : 0;
    // Alive player flag.
    out.alive = (player.isAlive()) ? 1 : 0;
    // Minor civilization player.
    out.minorCiv = (player.isMinorCiv()) ? 1 : 0;
    // Barbarian player.
    out.barbarian = (player.isBarbarian()) ? 1 : 0;
    // Embark ability.
    out.canEmbark = (player.CanEmbark()) ? 1 : 0;
    // Ocean crossing ability.
    out.canCrossOcean = (player.CanCrossOcean()) ? 1 : 0;
    // Mountain crossing ability.
    out.canCrossMountain = (player.CanCrossMountain()) ? 1 : 0;
    // Ice crossing ability.
    out.canCrossIce = (player.CanCrossIce()) ? 1 : 0;
    // Player team.
    out.team = static_cast<i8>(player.getTeam());
    // Trait owned by CvPlayerTraits.
    out.riverMovementBonus = (player.GetPlayerTraits()->IsRiverMovementBonus()) ? 1 : 0;
    // Trait owned by CvPlayerTraits.
    out.woodlandMovementBonus = (player.GetPlayerTraits()->IsWoodlandMovementBonus()) ? 1 : 0;
    // Trait owned by CvPlayerTraits.
    out.embarkedToLandFlatCost = (player.GetPlayerTraits()->IsEmbarkedToLandFlatCost()) ? 1 : 0;
    // Trait owned by CvPlayerTraits.
    out.fasterInHills = (player.GetPlayerTraits()->IsFasterInHills()) ? 1 : 0;
    // Trait owned by CvPlayerTraits.
    out.mountainPass = (player.GetPlayerTraits()->IsMountainPass()) ? 1 : 0;
    // Trait owned by CvPlayerTraits.
    out.traitFightWellDamaged = (player.GetPlayerTraits()->IsFightWellDamaged()) ? 1 : 0;
    return true;
}

bool CollectMinorRelationRecord(CvPlayer& player, CvMinorCivAI& minorCivAI, PlayerTypes otherPlayer, PlayerTypes capturingPlayer, MinorRelationRecord& out)
{
    // Related player.
    out.player = static_cast<i8>(otherPlayer);
    // Non-const native accessor.
    out.friends = (minorCivAI.IsFriends(capturingPlayer)) ? 1 : 0;
    // Capturing player alliance relation.
    out.allies = (minorCivAI.IsAllies(capturingPlayer)) ? 1 : 0;
    // Capturing player protection relation.
    out.protectedByMajor = (minorCivAI.IsProtectedByMajor(capturingPlayer)) ? 1 : 0;
    // Minor-civ owned relation.
    out.openBorders = (minorCivAI.IsPlayerHasOpenBorders(capturingPlayer)) ? 1 : 0;
    // Diplomacy AI war state.
    out.warState = static_cast<i8>(player.GetDiplomacyAI()->GetWarState(capturingPlayer));
    return true;
}

bool CollectZoneRecord(CvTacticalDominanceZone& zone, ZoneRecord& out)
{
    // Zone identifier.
    out.zoneId = static_cast<i32>(zone.GetZoneID());
    // Builder captures the native stored city identifier without changing its null convention.
    // cityId has no generated assignment because its capture mode is builder.
    // Area identifier.
    out.areaId = static_cast<i32>(zone.GetAreaID());
    // Friendly melee strength.
    out.friendlyMeleeStrength = static_cast<u32>(zone.GetFriendlyMeleeStrength());
    // Enemy melee strength.
    out.enemyMeleeStrength = static_cast<u32>(zone.GetEnemyMeleeStrength());
    // Friendly ranged strength.
    out.friendlyRangedStrength = static_cast<u32>(zone.GetFriendlyRangedStrength());
    // Enemy ranged strength.
    out.enemyRangedStrength = static_cast<u32>(zone.GetEnemyRangedStrength());
    // Friendly naval strength.
    out.friendlyNavalStrength = static_cast<u32>(zone.GetFriendlyNavalStrength());
    // Enemy naval strength.
    out.enemyNavalStrength = static_cast<u32>(zone.GetEnemyNavalStrength());
    // Friendly naval ranged strength.
    out.friendlyNavalRangedStrength = static_cast<u32>(zone.GetFriendlyNavalRangedStrength());
    // Enemy naval ranged strength.
    out.enemyNavalRangedStrength = static_cast<u32>(zone.GetEnemyNavalRangedStrength());
    // Friendly land unit count.
    out.friendlyUnitCount = static_cast<i32>(zone.GetTotalFriendlyUnitCount());
    // Enemy land unit count.
    out.enemyUnitCount = static_cast<i32>(zone.GetTotalEnemyUnitCount());
    // Neutral unit count.
    out.neutralUnitCount = static_cast<i32>(zone.GetNeutralUnitCount());
    // Neutral unit strength.
    out.neutralUnitStrength = static_cast<u32>(zone.GetNeutralStrength());
    // Friendly naval unit count.
    out.friendlyNavalUnitCount = static_cast<i32>(zone.GetFriendlyNavalUnitCount());
    // Enemy naval unit count.
    out.enemyNavalUnitCount = static_cast<i32>(zone.GetEnemyNavalUnitCount());
    // Dominance zone value.
    out.zoneValue = static_cast<i32>(zone.GetDominanceZoneValue());
    // Builder preserves the native fixed-point average coordinate.
    // avgX has no generated assignment because its capture mode is builder.
    // Builder preserves the native fixed-point average coordinate.
    // avgY has no generated assignment because its capture mode is builder.
    // Plots in the zone.
    out.plotCount = static_cast<i32>(zone.GetNumPlots());
    // Neighbor IDs in native vector order.
    // neighborRange has no generated assignment because its capture mode is builder.
    // Dominance territory type.
    out.territoryType = static_cast<u8>(zone.GetTerritoryType());
    // Overall dominance flag.
    out.overallDominanceFlag = static_cast<u8>(zone.GetOverallDominanceFlag());
    // Tactical posture.
    out.posture = static_cast<u8>(zone.GetPosture());
    // Zone owner.
    out.owner = static_cast<i8>(zone.GetOwner());
    return true;
}

bool CollectZoneNeighborRecord(ZoneNeighborRecord& out)
{
    // Child entry of ZoneRecord.neighborRange.
    // zoneId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectDangerPlayerRecord(PlayerTypes otherPlayer, DangerPlayerRecord& out)
{
    // Vox Deorum getter added beside the existing vanished-unit getter.
    // knownUnitRange has no generated assignment because its capture mode is builder.
    // Existing native vanished-unit set.
    // vanishedUnitRange has no generated assignment because its capture mode is builder.
    // Attacker owner player.
    out.player = static_cast<i8>(otherPlayer);
    return true;
}

bool CollectKnownAttackerRecord(KnownAttackerRecord& out)
{
    // Child entry of DangerPlayerRecord.knownUnitRange.
    // unitId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectVanishedAttackerRecord(VanishedAttackerRecord& out)
{
    // Child entry of DangerPlayerRecord.vanishedUnitRange.
    // unitId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignHeaderRecord(CvMilitaryAI& campaign, CvPlayer& player, CampaignHeaderRecord& out)
{
    // All threatened city IDs.
    // threatenedCityRange has no generated assignment because its capture mode is builder.
    // Threatened coastal city IDs.
    // coastalThreatenedCityRange has no generated assignment because its capture mode is builder.
    // Exposed city targets.
    // exposedCityRange has no generated assignment because its capture mode is builder.
    // Native military unit counter.
    // numLandUnits has no generated assignment because its capture mode is builder.
    // Native military unit counter.
    // numNavalUnits has no generated assignment because its capture mode is builder.
    // Native army unit counter.
    // numLandUnitsInArmies has no generated assignment because its capture mode is builder.
    // Native army unit counter.
    // numNavalUnitsInArmies has no generated assignment because its capture mode is builder.
    // Recommended land units.
    // recommendedLandUnits has no generated assignment because its capture mode is builder.
    // Recommended naval units.
    // recommendedNavalUnits has no generated assignment because its capture mode is builder.
    // Recommended explorer units.
    // recommendedExplorerUnits has no generated assignment because its capture mode is builder.
    // Player supply state.
    out.unitsSupplied = static_cast<i32>(player.GetNumUnitsSupplied());
    // Player supply state.
    out.unitsOutOfSupply = static_cast<i32>(player.GetNumUnitsOutOfSupply());
    // Non-const accessor, captured per domain.
    for (int index = 0; index < 8; ++index) {
        out.offensiveOperations[index] = 0;
    }
    if ((NUM_DOMAIN_TYPES) > VoxRlDomainCapacity) {
        return false;
    }
    for (int index = 0; index < (NUM_DOMAIN_TYPES); ++index) {
        out.offensiveOperations[index] = static_cast<i32>(player.GetNumOffensiveOperations(static_cast<DomainTypes>(index)));
    }
    // Treasury is filled by the operational block builder.
    // treasury has no generated assignment because its capture mode is builder.
    // Civs at war including native defaults.
    out.numCivsAtWar = static_cast<u8>(campaign.GetNumberCivsAtWarWith());
    return true;
}

bool CollectCampaignEnemyRecord(CampaignEnemyRecord& out)
{
    // Only valid enemy players are emitted.
    // player has no generated assignment because its capture mode is builder.
    // Per-enemy war state.
    // warState has no generated assignment because its capture mode is builder.
    // Per-enemy war score.
    // warScore has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignAttackTargetRecord(CampaignAttackTargetRecord& out)
{
    // Muster plot.
    // musterPlotIndex has no generated assignment because its capture mode is builder.
    // Staging plot.
    // stagingPlotIndex has no generated assignment because its capture mode is builder.
    // Target plot.
    // targetPlotIndex has no generated assignment because its capture mode is builder.
    // Path length.
    // pathLength has no generated assignment because its capture mode is builder.
    // Approach score.
    // approachScore has no generated assignment because its capture mode is builder.
    // Army type.
    // armyType has no generated assignment because its capture mode is builder.
    // Preferred target flag.
    // preferred has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignExposedCityRecord(CampaignExposedCityRecord& out)
{
    // Exposed city stable ID.
    // cityId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignOperationRecord(CampaignOperationRecord& out)
{
    // Operation ID.
    // id has no generated assignment because its capture mode is builder.
    // Muster x coordinate.
    // musterX has no generated assignment because its capture mode is builder.
    // Muster y coordinate.
    // musterY has no generated assignment because its capture mode is builder.
    // Target x coordinate.
    // targetX has no generated assignment because its capture mode is builder.
    // Target y coordinate.
    // targetY has no generated assignment because its capture mode is builder.
    // Turn started.
    // turnStarted has no generated assignment because its capture mode is builder.
    // Muster-to-target distance.
    // distanceMusterToTarget has no generated assignment because its capture mode is builder.
    // Native army IDs in vector order.
    // armyIdRange has no generated assignment because its capture mode is builder.
    // Operation type.
    // type has no generated assignment because its capture mode is builder.
    // Operation army type.
    // armyType has no generated assignment because its capture mode is builder.
    // Current operation state.
    // currentState has no generated assignment because its capture mode is builder.
    // Enemy player.
    // enemy has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignOperationArmyIdRecord(CampaignOperationArmyIdRecord& out)
{
    // Child entry of CampaignOperationRecord.armyIdRange.
    // armyId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignArmyRecord(CampaignArmyRecord& out)
{
    // Army ID.
    // id has no generated assignment because its capture mode is builder.
    // Formation type.
    // formation has no generated assignment because its capture mode is builder.
    // Goal x coordinate.
    // goalX has no generated assignment because its capture mode is builder.
    // Goal y coordinate.
    // goalY has no generated assignment because its capture mode is builder.
    // Filled formation slots.
    // slotsFilled has no generated assignment because its capture mode is builder.
    // Formation entries in native order.
    // formationRange has no generated assignment because its capture mode is builder.
    // Army AI state.
    // aiState has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignFormationEntryRecord(CampaignFormationEntryRecord& out)
{
    // Assigned unit ID.
    // unitId has no generated assignment because its capture mode is builder.
    // Required formation slot.
    // required has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignThreatenedCityRecord(CampaignThreatenedCityRecord& out)
{
    // Child entry of CampaignHeaderRecord.threatenedCityRange.
    // cityId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignCoastalThreatenedCityRecord(CampaignCoastalThreatenedCityRecord& out)
{
    // Child entry of CampaignHeaderRecord.coastalThreatenedCityRange.
    // cityId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectCampaignZoneRecord(CvTacticalDominanceZone& zone, CampaignZoneRecord& out)
{
    // Zone identifier at campaign capture time.
    out.zoneId = static_cast<i32>(zone.GetZoneID());
    // Builder captures the native stored city identifier without changing its null convention.
    // cityId has no generated assignment because its capture mode is builder.
    // Area identifier.
    out.areaId = static_cast<i32>(zone.GetAreaID());
    // Friendly melee strength.
    out.friendlyMeleeStrength = static_cast<u32>(zone.GetFriendlyMeleeStrength());
    // Enemy melee strength.
    out.enemyMeleeStrength = static_cast<u32>(zone.GetEnemyMeleeStrength());
    // Friendly ranged strength.
    out.friendlyRangedStrength = static_cast<u32>(zone.GetFriendlyRangedStrength());
    // Enemy ranged strength.
    out.enemyRangedStrength = static_cast<u32>(zone.GetEnemyRangedStrength());
    // Friendly naval strength.
    out.friendlyNavalStrength = static_cast<u32>(zone.GetFriendlyNavalStrength());
    // Enemy naval strength.
    out.enemyNavalStrength = static_cast<u32>(zone.GetEnemyNavalStrength());
    // Friendly naval ranged strength.
    out.friendlyNavalRangedStrength = static_cast<u32>(zone.GetFriendlyNavalRangedStrength());
    // Enemy naval ranged strength.
    out.enemyNavalRangedStrength = static_cast<u32>(zone.GetEnemyNavalRangedStrength());
    // Friendly land unit count.
    out.friendlyUnitCount = static_cast<i32>(zone.GetTotalFriendlyUnitCount());
    // Enemy land unit count.
    out.enemyUnitCount = static_cast<i32>(zone.GetTotalEnemyUnitCount());
    // Neutral unit count.
    out.neutralUnitCount = static_cast<i32>(zone.GetNeutralUnitCount());
    // Neutral unit strength.
    out.neutralUnitStrength = static_cast<u32>(zone.GetNeutralStrength());
    // Friendly naval unit count.
    out.friendlyNavalUnitCount = static_cast<i32>(zone.GetFriendlyNavalUnitCount());
    // Enemy naval unit count.
    out.enemyNavalUnitCount = static_cast<i32>(zone.GetEnemyNavalUnitCount());
    // Dominance zone value.
    out.zoneValue = static_cast<i32>(zone.GetDominanceZoneValue());
    // Builder preserves the native fixed-point average coordinate.
    // avgX has no generated assignment because its capture mode is builder.
    // Builder preserves the native fixed-point average coordinate.
    // avgY has no generated assignment because its capture mode is builder.
    // Plots in the zone.
    out.plotCount = static_cast<i32>(zone.GetNumPlots());
    // Neighbor IDs in native vector order at campaign capture time.
    // neighborRange has no generated assignment because its capture mode is builder.
    // Dominance territory type.
    out.territoryType = static_cast<u8>(zone.GetTerritoryType());
    // Overall dominance flag.
    out.overallDominanceFlag = static_cast<u8>(zone.GetOverallDominanceFlag());
    // Tactical posture.
    out.posture = static_cast<u8>(zone.GetPosture());
    // Zone owner.
    out.owner = static_cast<i8>(zone.GetOwner());
    return true;
}

bool CollectCampaignZoneNeighborRecord(CampaignZoneNeighborRecord& out)
{
    // Child entry of CampaignZoneRecord.neighborRange.
    // zoneId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestHeaderRecord(RequestHeaderRecord& out)
{
    // Caller decision identifier.
    // decisionId has no generated assignment because its capture mode is builder.
    // Target plot input.
    // targetPlotIndex has no generated assignment because its capture mode is builder.
    // Saved movement input.
    // saveMovement has no generated assignment because its capture mode is builder.
    // Caller classification.
    // callerType has no generated assignment because its capture mode is builder.
    // Retry attempt index.
    // attemptIndex has no generated assignment because its capture mode is builder.
    // Caller retry outcome.
    // retryOutcome has no generated assignment because its capture mode is builder.
    // Caller resolved intent.
    // resolvedIntent has no generated assignment because its capture mode is builder.
    // Changed or new unit records.
    // deltaUnitRange has no generated assignment because its capture mode is builder.
    // Changed plot records and visibility updates.
    // deltaPlotRange has no generated assignment because its capture mode is builder.
    // Changed city records.
    // deltaCityRange has no generated assignment because its capture mode is builder.
    // Removed unit IDs.
    // removedUnitRange has no generated assignment because its capture mode is builder.
    // Newly known attacker IDs.
    // knownAttackerRange has no generated assignment because its capture mode is builder.
    // Participants in caller order.
    // participantRange has no generated assignment because its capture mode is builder.
    // Unusable units dropped by the caller.
    // droppedUnitRange has no generated assignment because its capture mode is builder.
    // Attack-direction oracle rows.
    // attackOracleRange has no generated assignment because its capture mode is builder.
    // Danger-direction oracle rows.
    // dangerOracleRange has no generated assignment because its capture mode is builder.
    // Aggression-level input.
    // aggressionLevel has no generated assignment because its capture mode is builder.
    // Target-distance relevance input.
    // targetDistanceRelevant has no generated assignment because its capture mode is builder.
    // Return-to-start input.
    // returnToStartPositions has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestDeltaUnitRecord(RequestDeltaUnitRecord& out)
{
    // The builder writes the same UnitRecord fields as WORLD.
    // unitId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestDeltaPlotRecord(RequestDeltaPlotRecord& out)
{
    // The builder writes the same PlotDynamicRecord fields as WORLD.
    // plotIndex has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestDeltaCityRecord(RequestDeltaCityRecord& out)
{
    // The builder writes the same CityRecord fields as WORLD.
    // cityId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestRemovedUnitRecord(RequestRemovedUnitRecord& out)
{
    // Removed unit ID.
    // unitId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestKnownAttackerRecord(RequestKnownAttackerRecord& out)
{
    // Stable unit ID component of the native std::pair<PlayerTypes, int> identity.
    // unitId has no generated assignment because its capture mode is builder.
    // PlayerTypes component of the native std::pair<PlayerTypes, int> identity.
    // player has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestParticipantRecord(RequestParticipantRecord& out)
{
    // Participant unit ID.
    // unitId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestDroppedUnitRecord(RequestDroppedUnitRecord& out)
{
    // Dropped unit ID.
    // unitId has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestAttackOracleRecord(RequestAttackOracleRecord& out)
{
    // Attack key field.
    // attackerId has no generated assignment because its capture mode is builder.
    // Attack key field.
    // attackerPlotIndex has no generated assignment because its capture mode is builder.
    // Attack key field.
    // defenderId has no generated assignment because its capture mode is builder.
    // Attack key field.
    // garrisonId has no generated assignment because its capture mode is builder.
    // Damage-free base strength.
    // baseStrength has no generated assignment because its capture mode is builder.
    // Damage-free modifier sum.
    // modifierSum has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectRequestDangerOracleRecord(RequestDangerOracleRecord& out)
{
    // Defend key field.
    // defenderId has no generated assignment because its capture mode is builder.
    // Defend key field.
    // defenderPlotIndex has no generated assignment because its capture mode is builder.
    // Attacker or no-attacker sentinel from oracle enumeration.
    // attackerId has no generated assignment because its capture mode is builder.
    // Attacker plot or no-attacker sentinel.
    // attackerPlotIndex has no generated assignment because its capture mode is builder.
    // Damage-free base strength.
    // baseStrength has no generated assignment because its capture mode is builder.
    // Damage-free modifier sum.
    // modifierSum has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultAssignmentRecord(ResultAssignmentRecord& out)
{
    // Assigned unit ID.
    // unitId has no generated assignment because its capture mode is builder.
    // City damage.
    // cityDamage has no generated assignment because its capture mode is builder.
    // Self damage.
    // selfDamage has no generated assignment because its capture mode is builder.
    // Damaged city ID.
    // damagedCityId has no generated assignment because its capture mode is builder.
    // Per-unit damage values.
    // unitDamageRange has no generated assignment because its capture mode is builder.
    // Per-unit healing values.
    // unitHealingRange has no generated assignment because its capture mode is builder.
    // Native total score.
    // totalScore has no generated assignment because its capture mode is builder.
    // Origin plot index.
    // fromPlotIndex has no generated assignment because its capture mode is builder.
    // Destination plot index.
    // toPlotIndex has no generated assignment because its capture mode is builder.
    // Remaining movement.
    // remainingMoves has no generated assignment because its capture mode is builder.
    // Native assignment type.
    // assignmentType has no generated assignment because its capture mode is builder.
    // Native movement strategy.
    // moveType has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultReachabilityStartRecord(ResultReachabilityStartRecord& out)
{
    // Start key unit ID.
    // unitId has no generated assignment because its capture mode is builder.
    // Start key plot index.
    // plotIndex has no generated assignment because its capture mode is builder.
    // Start key movement.
    // movesLeft has no generated assignment because its capture mode is builder.
    // Freed zone-of-control plots in native order.
    // freedPlotRange has no generated assignment because its capture mode is builder.
    // Reachability records for this start key.
    // moveRange has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultReachabilityMoveRecord(ResultReachabilityMoveRecord& out)
{
    // Reachable plot index.
    // plotIndex has no generated assignment because its capture mode is builder.
    // Path length.
    // pathLength has no generated assignment because its capture mode is builder.
    // Remaining moves.
    // movesLeft has no generated assignment because its capture mode is builder.
    // Fixed-point normalized distance.
    // normalizedDistanceRaw has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultFreedPlotRecord(ResultFreedPlotRecord& out)
{
    // Child entry of ResultReachabilityStartRecord.freedPlotRange.
    // plotIndex has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultDangerEvidenceRecord(ResultDangerEvidenceRecord& out)
{
    // Touched plot index.
    // plotIndex has no generated assignment because its capture mode is builder.
    // Native improvement damage evidence.
    // improvementDamage has no generated assignment because its capture mode is builder.
    // Native fog count evidence.
    // fogCount has no generated assignment because its capture mode is builder.
    // Native attacker unit evidence.
    // unitRange has no generated assignment because its capture mode is builder.
    // Native city evidence.
    // cityRange has no generated assignment because its capture mode is builder.
    // Native civilian capture evidence.
    // captureUnitRange has no generated assignment because its capture mode is builder.
    // Native flat plot damage evidence.
    // flatPlotDamage has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultDangerUnitEvidenceRecord(ResultDangerUnitEvidenceRecord& out)
{
    // Native attacker unit ID component of the pair identity.
    // unitId has no generated assignment because its capture mode is builder.
    // PlayerTypes component of the native std::pair<PlayerTypes, int> identity.
    // player has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultDangerCityEvidenceRecord(ResultDangerCityEvidenceRecord& out)
{
    // Native danger city ID component of the pair identity.
    // cityId has no generated assignment because its capture mode is builder.
    // PlayerTypes component of the native std::pair<PlayerTypes, int> identity.
    // player has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultDangerCaptureEvidenceRecord(ResultDangerCaptureEvidenceRecord& out)
{
    // Native capture-unit ID component of the pair identity.
    // unitId has no generated assignment because its capture mode is builder.
    // PlayerTypes component of the native std::pair<PlayerTypes, int> identity.
    // player has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultOracleEvidenceRecord(ResultOracleEvidenceRecord& out)
{
    // Forecast attacker ID.
    // attackerId has no generated assignment because its capture mode is builder.
    // Forecast defender ID.
    // defenderId has no generated assignment because its capture mode is builder.
    // Forecast city ID or sentinel.
    // cityId has no generated assignment because its capture mode is builder.
    // Damage passed for the attacker.
    // attackerDamage has no generated assignment because its capture mode is builder.
    // Damage passed for the defender.
    // defenderDamage has no generated assignment because its capture mode is builder.
    // Native strength returned or used.
    // strength has no generated assignment because its capture mode is builder.
    // Native forecast damage result.
    // damage has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultMetadataRecord(ResultMetadataRecord& out)
{
    // Matching decision identifier.
    // decisionId has no generated assignment because its capture mode is builder.
    // Caller classification.
    // callerType has no generated assignment because its capture mode is builder.
    // Retry attempt index.
    // attemptIndex has no generated assignment because its capture mode is builder.
    // Outcome statistic aggregate.
    // searchStatistics has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultAssignmentDamageRecord(ResultAssignmentDamageRecord& out)
{
    // Damaged unit ID.
    // unitId has no generated assignment because its capture mode is builder.
    // Damage amount.
    // value has no generated assignment because its capture mode is builder.
    return true;
}

bool CollectResultAssignmentHealingRecord(ResultAssignmentHealingRecord& out)
{
    // Healed unit ID.
    // unitId has no generated assignment because its capture mode is builder.
    // Healing amount.
    // value has no generated assignment because its capture mode is builder.
    return true;
}
